import { AppNotification } from '../../types';

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'alert-1',
    title: 'New Leave Request',
    message: 'Neha Gupta applied for 3 days Casual Leave (CL) starting 12-Oct-2026.',
    type: 'danger',
    timestamp: '2 hours ago',
    read: false,
    link: 'LeaveApprovals',
  },
  {
    id: 'alert-2',
    title: 'Quotation Approved',
    message: 'Director approved quotation QT-BGSPL-2026-041 for Hindustan Zinc Ltd (₹47.20 Lakhs).',
    type: 'success',
    timestamp: '5 hours ago',
    read: false,
    link: 'ClientApprovals',
  },
  {
    id: 'alert-3',
    title: 'New vendor application received',
    message: 'Rajasthan Drilling Co. submitted vendor application for drilling services.',
    type: 'warning',
    timestamp: '6 hours ago',
    read: true,
    link: 'VendorApplications',
  },
  {
    id: 'alert-4',
    title: 'Document verified',
    message: 'Geological mapping report INV-2026-001 has been verified and moved to archive.',
    type: 'info',
    timestamp: '1 day ago',
    read: true,
    link: 'Documents',
  },
  {
    id: 'alert-5',
    title: 'New task assigned',
    message: 'Site visit and initial sampling for Bhilwara project.',
    type: 'info',
    timestamp: '1 day ago',
    read: true,
    link: 'Tasks',
  },
  {
    id: 'alert-6',
    title: 'Expense approval pending',
    message: 'Rohit Meena submitted travel reimbursement claim (₹12,450).',
    type: 'warning',
    timestamp: '1 day ago',
    read: true,
    link: 'Expenses',
  },
  {
    id: 'alert-7',
    title: 'New employee added',
    message: 'Test Kumar has been added to the system.',
    type: 'info',
    timestamp: '2 days ago',
    read: true,
    link: 'EmployeeDirectory',
  },
];
