import { Client, Lead, FollowUp, Quote } from '../../types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    name: 'Tata Steel Mining Corp',
    contactPerson: 'Debashis Sen (VP - Mining)',
    gstin: '08AAACT2727Q1ZB',
    pan: 'AAACT2727Q',
    email: 'contact@tatasteelmining.com',
    phone: '01482255011',
    billingAddress: 'Plot 44, Mining Complex, Sukinda, Jajpur',
    state: 'Odisha',
    location: 'Sukinda, Odisha',
    contractStatus: 'Active',
    totalValue: 4850000,
    activeProjectsCount: 2,
    createdAt: '2026-01-10',
  },
  {
    id: 'cli-002',
    name: 'Hindustan Zinc Ltd (Vedanta)',
    contactPerson: 'Arun Misra (Head - Exploration)',
    gstin: '08AAACH1234F1Z8',
    pan: 'AAACH1234F',
    email: 'procurement@hzl.vedanta.co.in',
    phone: '01482244199',
    billingAddress: 'Yashad Bhawan, Udaipur',
    state: 'Rajasthan',
    location: 'Udaipur, Rajasthan',
    contractStatus: 'Active',
    totalValue: 7200000,
    activeProjectsCount: 3,
    createdAt: '2026-02-15',
  },
  {
    id: 'cli-003',
    name: 'NMDC Limited',
    contactPerson: 'Amitava Mukherjee (Director - Commercial)',
    gstin: '36AAACN1958C1Z7',
    pan: 'AAACN1958C',
    email: 'contracts@nmdc.co.in',
    phone: '04023538711',
    billingAddress: 'Khanij Bhavan, Masab Tank, Hyderabad',
    state: 'Telangana',
    location: 'Hyderabad, Telangana',
    contractStatus: 'Under Onboarding',
    totalValue: 3100000,
    activeProjectsCount: 1,
    createdAt: '2026-03-01',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-001',
    title: 'Bhilwara Lead-Zinc Core Drilling & Resource Estimation',
    company: 'Hindustan Zinc Ltd',
    contactName: 'Rajesh Maloo',
    email: 'r.maloo@hzl.com',
    phone: '9829011223',
    estimatedValue: 4200000,
    stage: 'Qualified',
    notes: 'Require 3,000m diamond core drilling and G3-level geological resource modeling.',
    assignedTo: 'Vikram Patel',
    createdAt: '2026-09-12',
  },
  {
    id: 'lead-002',
    title: 'Khetri Copper Belt Geophysical IP/Resistivity Survey',
    company: 'Hindustan Copper Limited',
    contactName: 'Sanjay Banik',
    email: 's.banik@hindustancopper.com',
    phone: '9830114455',
    estimatedValue: 1850000,
    stage: 'Proposal Sent',
    notes: 'Time-domain induced polarization survey across 45 line-km.',
    assignedTo: 'Dr. Rajesh Bansal',
    createdAt: '2026-09-18',
  },
  {
    id: 'lead-003',
    title: 'Bellary Iron Ore Topographical Drone LiDAR Mapping',
    company: 'Jindal Steel & Power',
    contactName: 'Anand Reddy',
    email: 'a.reddy@jspl.com',
    phone: '9848099887',
    estimatedValue: 950000,
    stage: 'New',
    notes: 'High-precision DGPS ground control and UAV photogrammetry over 12 sq km.',
    assignedTo: 'Vikram Patel',
    createdAt: '2026-09-28',
  },
  {
    id: 'lead-004',
    title: 'Rajpura Dariba Lead-Zinc Stage 5 Core Analysis',
    company: 'Vedanta Resources Ltd',
    contactName: 'Sunil Duggal',
    email: 's.duggal@vedanta.co.in',
    phone: '9829044556',
    estimatedValue: 3600000,
    quoteValue: 3600000,
    stage: 'Negotiation',
    quoteStatus: 'Accepted',
    approval: { quoteAccepted: true, poReceived: true, advanceReceived: false, agreementSigned: false },
    notes: 'Quotation accepted by procurement committee. PO received, awaiting 50% advance mobilization deposit.',
    assignedTo: 'Vikram Patel',
    createdAt: '2026-09-20',
  },
  {
    id: 'lead-005',
    title: 'Sukinda Valley Chromite Deep Geotechnical Logging',
    company: 'Tata Steel Mining Corp',
    contactName: 'Debashis Sen',
    email: 'd.sen@tatasteelmining.com',
    phone: '9831099221',
    estimatedValue: 2450000,
    quoteValue: 2450000,
    stage: 'Negotiation',
    quoteStatus: 'Accepted',
    approval: { quoteAccepted: true, poReceived: true, advanceReceived: true, agreementSigned: false },
    notes: 'Advance payment of ₹12.25L received via RTGS. Tripartite service agreement sent for final execution.',
    assignedTo: 'Dr. Rajesh Bansal',
    createdAt: '2026-09-22',
  },
  {
    id: 'lead-006',
    title: 'Zawar Silver-Zinc Underground Wireline Logging',
    company: 'Hindustan Zinc Ltd',
    contactName: 'Arun Misra',
    email: 'a.misra@hzl.com',
    phone: '9829011400',
    estimatedValue: 4800000,
    quoteValue: 4800000,
    stage: 'Won',
    quoteStatus: 'Accepted',
    approval: { quoteAccepted: true, poReceived: true, advanceReceived: true, agreementSigned: true },
    notes: 'All 4 statutory gates cleared: PO received, advance deposited, agreement executed. Closed as Won contract.',
    assignedTo: 'Vikram Patel',
    createdAt: '2026-09-25',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'fu-001',
    leadId: 'lead-001',
    clientName: 'Hindustan Zinc Ltd',
    date: '2026-10-05',
    interactionType: 'Meeting',
    outcome: 'Presented draft technical methodology; waiting for technical committee clearance.',
    notes: 'Discuss mobilized rig availability in Rajasthan.',
    status: 'Pending',
  },
  {
    id: 'fu-002',
    leadId: 'lead-002',
    clientName: 'Hindustan Copper Limited',
    date: '2026-10-03',
    interactionType: 'Phone Call',
    outcome: 'Commercial quotation under review by General Manager (Mining).',
    notes: 'Follow up on technical line items clarification.',
    status: 'Pending',
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'q-001',
    quoteNo: 'QT-BGSPL-2026-041',
    clientId: 'cli-002',
    clientName: 'Hindustan Zinc Ltd',
    projectTitle: 'Bhilwara Zinc Exploration Block G3',
    date: '2026-09-20',
    lineItems: [
      { id: 'li-1', description: 'HQ Diamond Core Drilling', unit: 'Meters', quantity: 2000, rate: 1450, amount: 2900000 },
      { id: 'li-2', description: 'Core Logging & Geological Sampling', unit: 'Meters', quantity: 2000, rate: 250, amount: 500000 },
      { id: 'li-3', description: 'ICP-MS 35 Element Geochemical Assay', unit: 'Samples', quantity: 400, rate: 850, amount: 340000 },
      { id: 'li-4', description: '3D Geological Modeling (Leapfrog)', unit: 'Lumpsum', quantity: 1, rate: 350000, amount: 350000 },
    ],
    subtotal: 4090000,
    discount: 90000,
    gstRate: 0.18,
    gstAmount: 720000,
    total: 4720000,
    status: 'Approved',
    requiresDirectorApproval: true,
    approvalRemarks: 'Director approved for client transmission with standard payment milestones.',
  },
  {
    id: 'q-002',
    quoteNo: 'QT-BGSPL-2026-042',
    clientId: 'cli-001',
    clientName: 'Tata Steel Mining Corp',
    projectTitle: 'Sukinda Chromite Geotechnical Borehole Study',
    date: '2026-09-25',
    lineItems: [
      { id: 'li-10', description: 'Standard Penetration Test (SPT) Boreholes', unit: 'Meters', quantity: 600, rate: 1200, amount: 720000 },
      { id: 'li-11', description: 'Rock Mechanics Testing (UCS/Tensile)', unit: 'Samples', quantity: 80, rate: 1500, amount: 120000 },
    ],
    subtotal: 840000,
    discount: 40000,
    gstRate: 0.18,
    gstAmount: 144000,
    total: 944000,
    status: 'Pending Approval',
    requiresDirectorApproval: true,
  },
];
