import { Project } from '../../types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-001',
    projectCode: 'PRJ-GEO-2026-001',
    clientId: 'cli-002',
    clientName: 'Hindustan Zinc Ltd',
    title: 'Bhilwara Lead-Zinc Exploration Block',
    name: 'Bhilwara Lead-Zinc Exploration Block',
    service: 'Mineral Exploration & Resources',
    location: 'Bhilwara, Rajasthan',
    site: 'Bhilwara · Pit 2 North Block',
    authority: 'Department of Mines & Geology, Rajasthan',
    code: 'DMG',
    refBase: 'DMG/RAJ/2026/1420',
    baselineBudget: 4200000,
    currentStage: 3,
    stageIndex: 2,
    stageName: 'Stage 3: Task Execution',
    status: 'In progress',
    startDate: '2026-08-01',
    startedOn: '2026-08-01',
    endDate: '2026-12-15',
    dueOn: '2026-11-20',
    team: {
      coordinator: 'Kritika Gupta',
      teamLead: 'Dr. Sunita Meena',
      members: ['Ajay Kumar', 'Deepak Soni', 'Imran Ali'],
    },
    stages: [
      { stage: 1, name: 'Stage 1: Allocation', key: 'allocation', status: 'Completed', completedAt: '2026-08-05' },
      { stage: 2, name: 'Stage 2: Planning', key: 'planning', status: 'Completed', completedAt: '2026-08-20' },
      { stage: 3, name: 'Stage 3: Task Execution', key: 'tasks', status: 'In Progress' },
      { stage: 4, name: 'Stage 4: Deliverable Submission', key: 'submission', status: 'Pending' },
      { stage: 5, name: 'Stage 5: Client Approval', key: 'approval', status: 'Pending' },
      { stage: 6, name: 'Stage 6: Invoicing', key: 'invoicing', status: 'Pending' },
      { stage: 7, name: 'Stage 7: Project Closure', key: 'closure', status: 'Pending' },
    ],
    milestones: [
      { key: 'kickoff', label: 'Kick-off & data collection', date: '2026-08-08', done: true },
      { key: 'field', label: 'Field survey & sampling', date: '2026-09-12', done: true },
      { key: 'analysis', label: 'Analysis & modelling', date: '2026-10-18', done: false },
      { key: 'report', label: 'Report preparation', date: '2026-11-05', done: false },
      { key: 'submission', label: 'Submission to authority', date: '2026-11-20', done: false },
    ],
    approvals: [
      { key: 'filed', label: 'Exploration report submitted', days: 0, date: null, done: false, letter: 'Acknowledgement of exploration report' },
      { key: 'scrutiny', label: 'Scrutiny by the Directorate', days: 24, date: null, done: false },
      { key: 'granted', label: 'Geological report accepted', days: 52, date: null, done: false, letter: 'Acceptance of geological report' },
    ],
    tasks: [
      { id: 't-1', projectId: 'prj-001', key: 'kickoff', title: 'Kick-off & data collection', assigneeName: 'Dr. Sunita Meena', assignee: 'Dr. Sunita Meena', dueDate: '2026-08-08', due: '2026-08-08', priority: 'High', status: 'Completed', standard: true, doneOn: '2026-08-08' },
      { id: 't-2', projectId: 'prj-001', key: 'field', title: 'Field survey & sampling', assigneeName: 'Ajay Kumar', assignee: 'Ajay Kumar', dueDate: '2026-09-12', due: '2026-09-12', priority: 'Urgent', status: 'Completed', standard: true, doneOn: '2026-09-12' },
      { id: 't-3', projectId: 'prj-001', key: 'analysis', title: 'Analysis & modelling', assigneeName: 'Dr. Sunita Meena', assignee: 'Dr. Sunita Meena', dueDate: '2026-10-01', due: '2026-10-01', priority: 'Urgent', status: 'In Progress', standard: true, overdue: true },
      { id: 't-4', projectId: 'prj-001', key: 'report', title: 'Report preparation', assigneeName: 'Dr. Sunita Meena', assignee: 'Dr. Sunita Meena', dueDate: '2026-11-05', due: '2026-11-05', priority: 'High', status: 'Todo', standard: true },
      { id: 't-5', projectId: 'prj-001', key: 'submission', title: 'Submission to authority', assigneeName: 'Kritika Gupta', assignee: 'Kritika Gupta', dueDate: '2026-11-20', due: '2026-11-20', priority: 'Medium', status: 'Todo', standard: true },
      { id: 't-6', projectId: 'prj-001', title: 'Core drilling & logging HQ coring (0-150m)', assigneeName: 'Imran Ali', assignee: 'Imran Ali', dueDate: '2026-10-08', due: '2026-10-08', priority: 'High', status: 'In Progress', standard: false },
    ],
    fieldVisits: [
      {
        id: 'FV-01',
        date: '2026-08-25',
        by: 'Ajay Kumar',
        activity: 'Geological mapping',
        location: 'Pit 2, north block',
        notes: 'Detailed structural mapping of shear zone completed with 1:5000 topo sheet.',
        files: [
          { id: 'fv1-a', name: 'shear_zone_mapping_photos.jpg', size: 2840000, type: 'image/jpeg', shared: true },
          { id: 'fv1-b', name: 'structural_readings.csv', size: 24500, type: 'text/csv', shared: true },
        ],
      },
      {
        id: 'FV-02',
        date: '2026-09-08',
        by: 'Imran Ali',
        activity: 'Core drilling & logging',
        location: 'Borehole BH-04 drill pad',
        notes: 'HQ cored down to 88m. Good core recovery in mineralized zone (approx 92%).',
        files: [
          { id: 'fv2-a', name: 'bh04_core_boxes.jpg', size: 3410000, type: 'image/jpeg', shared: true },
        ],
      },
    ],
    deliverables: [
      { id: 'del-1', projectId: 'prj-001', title: 'Interim Geological Lithologs Pack v1', version: 'v1.0', fileName: 'Bhilwara_Interim_Lithologs_v1.pdf', submissionDate: '2026-09-15', status: 'Client Approved', fileSize: '14.2 MB' },
      { id: 'del-2', projectId: 'prj-001', title: 'Laboratory Geochemical Assay Batch A', version: 'v1.2', fileName: 'Assay_Results_BatchA.xlsx', submissionDate: '2026-09-28', status: 'Submitted', fileSize: '3.8 MB' },
    ],
    letters: [
      { id: 'GL-101', title: 'Exploration Inspection Notice', authority: 'Department of Mines & Geology, Rajasthan', ref: 'DMG/RAJ/2026/1420/INSP', date: '2026-09-22', sharedOn: '2026-09-23' },
    ],
    closure: {
      steps: [
        { key: 'handover', label: 'Final report and approval handed over to the client', done: false, date: null },
        { key: 'payment', label: 'Final payment received', done: false, date: null },
        { key: 'archive', label: 'Field data and documents archived', done: false, date: null },
        { key: 'feedback', label: 'Client feedback taken', done: false, date: null },
      ],
      closedOn: null,
      note: null,
    },
    submission: {
      mode: 'By hand at the office',
      ackNo: 'DMG/RAJ/2026/1420/ACK',
      date: '2026-11-20',
      files: [],
    },
    documents: [
      { id: 'doc-01', name: 'Bhilwara_Topographical_Survey_Grid.dwg', size: 4800000, type: 'application/acad', category: 'Maps & drawings', addedOn: '2026-08-15', shared: true },
      { id: 'doc-02', name: 'Environmental_Baseline_Report_Interim.pdf', size: 2100000, type: 'application/pdf', category: 'Report', addedOn: '2026-09-10', shared: true },
    ],
    history: [
      { id: 'h-1', kind: 'created', date: '2026-08-01', text: 'Project created — work confirmed by Hindustan Zinc Ltd' },
      { id: 'h-2', kind: 'team', date: '2026-08-05', text: 'Team allocated: Kritika Gupta (coordinator), Dr. Sunita Meena (team lead), Ajay Kumar, Deepak Soni' },
      { id: 'h-3', kind: 'milestone', date: '2026-08-08', text: 'Kick-off & data collection done' },
      { id: 'h-4', kind: 'milestone', date: '2026-09-12', text: 'Field survey & sampling done' },
    ],
    now: { label: 'Analysis & modelling', date: '2026-10-18' },
  },
  {
    id: 'prj-002',
    projectCode: 'PRJ-GEO-2026-002',
    clientId: 'cli-001',
    clientName: 'Tata Steel Mining Corp',
    title: 'Sukinda Chromite Geotechnical Study',
    name: 'Sukinda Chromite Geotechnical Study',
    service: 'Geotechnical Services',
    location: 'Jajpur, Odisha',
    site: 'Sukinda Valley · Quarry 3 Bench',
    authority: 'Directorate General of Mines Safety',
    code: 'DGMS',
    refBase: 'DGMS/ORI/2026/3310',
    baselineBudget: 944000,
    currentStage: 2,
    stageIndex: 1,
    stageName: 'Stage 2: Planning',
    status: 'In progress',
    startDate: '2026-09-15',
    startedOn: '2026-09-15',
    endDate: '2026-11-30',
    dueOn: '2026-11-15',
    team: {
      coordinator: 'A. Singh',
      teamLead: null,
      members: [],
    },
    stages: [
      { stage: 1, name: 'Stage 1: Allocation', key: 'allocation', status: 'Completed', completedAt: '2026-09-18' },
      { stage: 2, name: 'Stage 2: Planning', key: 'planning', status: 'In Progress' },
      { stage: 3, name: 'Stage 3: Task Execution', key: 'tasks', status: 'Pending' },
      { stage: 4, name: 'Stage 4: Deliverable Submission', key: 'submission', status: 'Pending' },
      { stage: 5, name: 'Stage 5: Client Approval', key: 'approval', status: 'Pending' },
      { stage: 6, name: 'Stage 6: Invoicing', key: 'invoicing', status: 'Pending' },
      { stage: 7, name: 'Stage 7: Project Closure', key: 'closure', status: 'Pending' },
    ],
    milestones: [
      { key: 'kickoff', label: 'Kick-off & data collection', date: '2026-09-22', done: true },
      { key: 'field', label: 'Field survey & sampling', date: '2026-10-10', done: false },
      { key: 'analysis', label: 'Analysis & modelling', date: '2026-10-28', done: false },
      { key: 'report', label: 'Report preparation', date: '2026-11-08', done: false },
      { key: 'submission', label: 'Submission to authority', date: '2026-11-15', done: false },
    ],
    approvals: [
      { key: 'filed', label: 'Slope stability report submitted', days: 0, date: null, done: false, letter: 'Acknowledgement of report' },
      { key: 'scrutiny', label: 'DGMS review', days: 25, date: null, done: false },
      { key: 'granted', label: 'Permission granted', days: 48, date: null, done: false, letter: 'Permission under Reg. 106' },
    ],
    tasks: [
      { id: 't-10', projectId: 'prj-002', key: 'field', title: 'Bench stability mapping and rock joint analysis', assigneeName: 'Deepak Soni', assignee: 'Deepak Soni', dueDate: '2026-10-10', due: '2026-10-10', priority: 'High', status: 'In Progress', standard: true },
    ],
    fieldVisits: [],
    deliverables: [],
    letters: [],
    closure: {
      steps: [
        { key: 'handover', label: 'Final report and approval handed over to the client', done: false, date: null },
        { key: 'payment', label: 'Final payment received', done: false, date: null },
        { key: 'archive', label: 'Field data and documents archived', done: false, date: null },
        { key: 'feedback', label: 'Client feedback taken', done: false, date: null },
      ],
      closedOn: null,
      note: null,
    },
    submission: {
      mode: 'By hand at the office',
      ackNo: '',
      date: '2026-11-15',
      files: [],
    },
    documents: [],
    history: [
      { id: 'h-10', kind: 'created', date: '2026-09-15', text: 'Project created — work confirmed by Tata Steel Mining Corp' },
      { id: 'h-11', kind: 'team', date: '2026-09-18', text: 'Coordinator allocated: A. Singh' },
    ],
    now: { label: 'Choose the team lead and field team', date: '2026-10-06' },
  },
  {
    id: 'prj-003',
    projectCode: 'PRJ-GEO-2026-003',
    clientId: 'cli-001',
    clientName: 'Vedanta Resources Ltd',
    title: 'Khetri Copper PARIVESH Clearance',
    name: 'Khetri Copper PARIVESH Clearance',
    service: 'Environment, Community & Permitting',
    location: 'Jhunjhunu, Rajasthan',
    site: 'Khetri Copper Complex',
    authority: 'SEIAA / MoEFCC (PARIVESH)',
    code: 'SEIAA',
    refBase: 'SEIAA/RAJ/2026/8841',
    baselineBudget: 3500000,
    currentStage: 5,
    stageIndex: 4,
    stageName: 'Stage 5: Client Approval',
    status: 'Awaiting approval',
    startDate: '2026-05-10',
    startedOn: '2026-05-10',
    endDate: '2026-11-30',
    dueOn: '2026-09-15',
    team: {
      coordinator: 'Kritika Gupta',
      teamLead: 'M. Khan',
      members: ['Pooja Meena', 'Ajay Kumar'],
    },
    stages: [
      { stage: 1, name: 'Stage 1: Allocation', key: 'allocation', status: 'Completed', completedAt: '2026-05-15' },
      { stage: 2, name: 'Stage 2: Planning', key: 'planning', status: 'Completed', completedAt: '2026-05-25' },
      { stage: 3, name: 'Stage 3: Task Execution', key: 'tasks', status: 'Completed', completedAt: '2026-09-10' },
      { stage: 4, name: 'Stage 4: Deliverable Submission', key: 'submission', status: 'Completed', completedAt: '2026-09-15' },
      { stage: 5, name: 'Stage 5: Client Approval', key: 'approval', status: 'In Progress' },
      { stage: 6, name: 'Stage 6: Invoicing', key: 'invoicing', status: 'Pending' },
      { stage: 7, name: 'Stage 7: Project Closure', key: 'closure', status: 'Pending' },
    ],
    milestones: [
      { key: 'kickoff', label: 'Kick-off & baseline review', date: '2026-05-28', done: true },
      { key: 'field', label: 'Air & noise sampling', date: '2026-07-15', done: true },
      { key: 'analysis', label: 'EIA modeling & prediction', date: '2026-08-20', done: true },
      { key: 'report', label: 'Comprehensive EIA report', date: '2026-09-10', done: true },
      { key: 'submission', label: 'Submission on PARIVESH portal', date: '2026-09-15', done: true },
    ],
    approvals: [
      { key: 'filed', label: 'EC application filed on PARIVESH', days: 0, date: '2026-09-15', done: true, letter: 'Acknowledgement of EC application' },
      { key: 'hearing', label: 'Public hearing held', days: 30, date: '2026-10-15', done: false, letter: 'Minutes of public hearing' },
      { key: 'scrutiny', label: 'SEAC appraisal', days: 55, date: '2026-11-10', done: false },
      { key: 'granted', label: 'Environmental Clearance granted', days: 80, date: '2026-12-05', done: false, letter: 'Environmental Clearance letter' },
    ],
    tasks: [
      { id: 't-20', projectId: 'prj-003', key: 'submission', title: 'Filing on PARIVESH portal with digital signatures', assigneeName: 'Kritika Gupta', assignee: 'Kritika Gupta', dueDate: '2026-09-15', due: '2026-09-15', priority: 'High', status: 'Completed', standard: true, doneOn: '2026-09-15' },
      { id: 't-21', projectId: 'prj-003', key: 'hearing', title: 'Prepare presentation & attend Public Hearing at Khetri', assigneeName: 'M. Khan', assignee: 'M. Khan', dueDate: '2026-10-14', due: '2026-10-14', priority: 'Urgent', status: 'In Progress', standard: false },
    ],
    fieldVisits: [
      {
        id: 'FV-20',
        date: '2026-07-14',
        by: 'Pooja Meena',
        activity: 'Baseline air & water sampling',
        location: 'Khetri plant boundary buffer zone',
        notes: '24-hour continuous particulate matter PM10 & PM2.5 sampling conducted. Ambient noise levels recorded.',
        files: [
          { id: 'fv20-a', name: 'khetri_ambient_air_log.csv', size: 45000, type: 'text/csv', shared: true },
        ],
      },
    ],
    deliverables: [
      { id: 'del-20', projectId: 'prj-003', title: 'Draft Environmental Impact Assessment (EIA)', version: 'v2.1', fileName: 'Khetri_Draft_EIA_v2.1.pdf', submissionDate: '2026-09-10', status: 'Client Approved', fileSize: '28.4 MB' },
    ],
    letters: [
      { id: 'GL-301', title: 'PARIVESH Portal Application Acknowledgement', authority: 'SEIAA / MoEFCC', ref: 'SEIAA/RAJ/2026/8841/ACK', date: '2026-09-15', stepKey: 'filed', sharedOn: '2026-09-16' },
      { id: 'GL-302', title: 'Public Hearing Schedule Notice', authority: 'Rajasthan State Pollution Control Board', ref: 'RSPCB/ENV/PH/2026/410', date: '2026-09-28', sharedOn: '2026-09-29' },
    ],
    closure: {
      steps: [
        { key: 'handover', label: 'Final report and approval handed over to the client', done: false, date: null },
        { key: 'payment', label: 'Final payment received', done: false, date: null },
        { key: 'archive', label: 'Field data and documents archived', done: false, date: null },
        { key: 'feedback', label: 'Client feedback taken', done: false, date: null },
      ],
      closedOn: null,
      note: null,
    },
    submission: {
      mode: 'PARIVESH portal',
      ackNo: 'SEIAA/RAJ/2026/8841/ACK',
      date: '2026-09-15',
      by: 'Kritika Gupta',
      files: [{ id: 'sub-3', name: 'PARIVESH_Uploaded_EIA_Pack.pdf', size: 18200000, type: 'application/pdf', shared: true }],
    },
    documents: [
      { id: 'doc-31', name: 'Comprehensive_EIA_Report_Final.pdf', size: 28400000, type: 'application/pdf', category: 'Report', addedOn: '2026-09-10', shared: true },
    ],
    history: [
      { id: 'h-31', kind: 'created', date: '2026-05-10', text: 'Project created — work confirmed by Vedanta Resources Ltd' },
      { id: 'h-32', kind: 'submission', date: '2026-09-15', text: 'Submitted to SEIAA / MoEFCC via PARIVESH portal · Ack. SEIAA/RAJ/2026/8841/ACK' },
      { id: 'h-33', kind: 'letter', date: '2026-09-15', text: 'Letter received: PARIVESH Portal Application Acknowledgement' },
      { id: 'h-34', kind: 'letter', date: '2026-09-28', text: 'Letter received: Public Hearing Schedule Notice' },
    ],
    now: { label: 'Public hearing held', date: '2026-10-15' },
  },
  {
    id: 'prj-004',
    projectCode: 'PRJ-GEO-2026-004',
    clientId: 'cli-002',
    clientName: 'Adani Cement Ltd',
    title: 'Jaisalmer Limestone DGPS Boundary Survey',
    name: 'Jaisalmer Limestone DGPS Boundary Survey',
    service: 'Remote Sensing, GIS & Aerial Mapping',
    location: 'Jaisalmer, Rajasthan',
    site: 'Sanu Block IV Limestone Mine',
    authority: 'Department of Mines & Geology, Rajasthan',
    code: 'DMG',
    refBase: 'DMG/JAI/2026/6612',
    baselineBudget: 1250000,
    currentStage: 1,
    stageIndex: 0,
    stageName: 'Stage 1: Allocation',
    status: 'Not started',
    startDate: '2026-10-01',
    startedOn: null,
    endDate: '2026-12-31',
    dueOn: '2026-11-30',
    team: {
      coordinator: null,
      teamLead: null,
      members: [],
    },
    stages: [
      { stage: 1, name: 'Stage 1: Allocation', key: 'allocation', status: 'In Progress' },
      { stage: 2, name: 'Stage 2: Planning', key: 'planning', status: 'Pending' },
      { stage: 3, name: 'Stage 3: Task Execution', key: 'tasks', status: 'Pending' },
      { stage: 4, name: 'Stage 4: Deliverable Submission', key: 'submission', status: 'Pending' },
      { stage: 5, name: 'Stage 5: Client Approval', key: 'approval', status: 'Pending' },
      { stage: 6, name: 'Stage 6: Invoicing', key: 'invoicing', status: 'Pending' },
      { stage: 7, name: 'Stage 7: Project Closure', key: 'closure', status: 'Pending' },
    ],
    milestones: [
      { key: 'kickoff', label: 'Kick-off & boundary records', date: '2026-10-10', done: false },
      { key: 'field', label: 'DGPS pillar survey & drone flight', date: '2026-10-25', done: false },
      { key: 'analysis', label: 'GIS processing & boundary maps', date: '2026-11-12', done: false },
      { key: 'report', label: 'Boundary demarcation report', date: '2026-11-25', done: false },
      { key: 'submission', label: 'Submission to DMG', date: '2026-11-30', done: false },
    ],
    approvals: [
      { key: 'filed', label: 'Survey maps submitted', days: 0, date: null, done: false, letter: 'Acknowledgement of survey maps' },
      { key: 'inspection', label: 'DGPS pillar verification', days: 18, date: null, done: false },
      { key: 'granted', label: 'Lease maps approved', days: 38, date: null, done: false, letter: 'Approval of lease boundary maps' },
    ],
    tasks: [],
    fieldVisits: [],
    deliverables: [],
    letters: [],
    closure: {
      steps: [
        { key: 'handover', label: 'Final report and approval handed over to the client', done: false, date: null },
        { key: 'payment', label: 'Final payment received', done: false, date: null },
        { key: 'archive', label: 'Field data and documents archived', done: false, date: null },
        { key: 'feedback', label: 'Client feedback taken', done: false, date: null },
      ],
      closedOn: null,
      note: null,
    },
    submission: {
      mode: 'By hand at the office',
      ackNo: '',
      date: '2026-11-30',
      files: [],
    },
    documents: [],
    history: [
      { id: 'h-40', kind: 'created', date: '2026-10-01', text: 'Project created — work confirmed by Adani Cement Ltd' },
    ],
    now: { label: 'Assign a project coordinator', date: '2026-10-01' },
  },
  {
    id: 'prj-005',
    projectCode: 'PRJ-GEO-2025-044',
    clientId: 'cli-001',
    clientName: 'JSW Steel Mining',
    title: 'Bellary Iron Ore Mining Plan Approval',
    name: 'Bellary Iron Ore Mining Plan Approval',
    service: 'Mine Planning & Prefeasibility Study',
    location: 'Bellary, Karnataka',
    site: 'Sandur Sector Mining Lease 2814',
    authority: 'Indian Bureau of Mines',
    code: 'IBM',
    refBase: 'IBM/BLR/2025/1190',
    baselineBudget: 5500000,
    currentStage: 7,
    stageIndex: 6,
    stageName: 'Stage 7: Project Closure',
    status: 'Completed',
    startDate: '2025-11-01',
    startedOn: '2025-11-01',
    endDate: '2026-09-20',
    dueOn: '2026-05-15',
    team: {
      coordinator: 'N. Rathore',
      teamLead: 'S. Choudhary',
      members: ['Deepak Soni', 'Ajay Kumar'],
    },
    stages: [
      { stage: 1, name: 'Stage 1: Allocation', key: 'allocation', status: 'Completed', completedAt: '2025-11-05' },
      { stage: 2, name: 'Stage 2: Planning', key: 'planning', status: 'Completed', completedAt: '2025-11-20' },
      { stage: 3, name: 'Stage 3: Task Execution', key: 'tasks', status: 'Completed', completedAt: '2026-04-30' },
      { stage: 4, name: 'Stage 4: Deliverable Submission', key: 'submission', status: 'Completed', completedAt: '2026-05-15' },
      { stage: 5, name: 'Stage 5: Client Approval', key: 'approval', status: 'Completed', completedAt: '2026-08-10' },
      { stage: 6, name: 'Stage 6: Invoicing', key: 'invoicing', status: 'Completed', completedAt: '2026-09-05' },
      { stage: 7, name: 'Stage 7: Project Closure', key: 'closure', status: 'Completed', completedAt: '2026-09-20' },
    ],
    milestones: [
      { key: 'kickoff', label: 'Kick-off & pit design parameters', date: '2025-11-25', done: true },
      { key: 'field', label: 'Drone survey & pit bench measurement', date: '2026-01-15', done: true },
      { key: 'analysis', label: 'Mine scheduling & dump design', date: '2026-03-20', done: true },
      { key: 'report', label: 'Final Progressive Mine Closure Plan', date: '2026-04-30', done: true },
      { key: 'submission', label: 'Filing on IBM portal', date: '2026-05-15', done: true },
    ],
    approvals: [
      { key: 'filed', label: 'Mining plan submitted', days: 0, date: '2026-05-15', done: true, letter: 'Acknowledgement of mining plan' },
      { key: 'inspection', label: 'IBM site inspection', days: 26, date: '2026-06-12', done: true, letter: 'Site inspection notice' },
      { key: 'granted', label: 'Mining plan approved', days: 58, date: '2026-08-10', done: true, letter: 'Mining plan approval letter' },
    ],
    tasks: [
      { id: 't-50', projectId: 'prj-005', key: 'report', title: 'Prepare Progressive Mine Closure Plan under Rule 23', assigneeName: 'S. Choudhary', assignee: 'S. Choudhary', dueDate: '2026-04-30', due: '2026-04-30', priority: 'High', status: 'Completed', standard: true, doneOn: '2026-04-30' },
    ],
    fieldVisits: [
      {
        id: 'FV-50',
        date: '2026-01-14',
        by: 'Deepak Soni',
        activity: 'Drone survey of the lease',
        location: 'Pit 1 & North Waste Dump',
        notes: 'High-resolution photogrammetric survey completed with ground control points verified.',
        files: [
          { id: 'fv50-a', name: 'sandur_pit_orthomosaic.tif', size: 14500000, type: 'image/tiff', shared: true },
        ],
      },
    ],
    deliverables: [
      { id: 'del-50', projectId: 'prj-005', title: 'Approved Mining Plan and PMCP Document Pack', version: 'vFinal', fileName: 'Bellary_Approved_Mining_Plan_IBM.pdf', submissionDate: '2026-08-15', status: 'Client Approved', fileSize: '42.1 MB' },
    ],
    letters: [
      { id: 'GL-501', title: 'Mining Plan Formal Approval Letter', authority: 'Indian Bureau of Mines', ref: 'IBM/BLR/MP/2026/4921', date: '2026-08-10', stepKey: 'granted', sharedOn: '2026-08-12' },
    ],
    closure: {
      steps: [
        { key: 'handover', label: 'Final report and approval handed over to the client', done: true, date: '2026-08-25' },
        { key: 'payment', label: 'Final payment received', done: true, date: '2026-09-05' },
        { key: 'archive', label: 'Field data and documents archived', done: true, date: '2026-09-12' },
        { key: 'feedback', label: 'Client feedback taken', done: true, date: '2026-09-18' },
      ],
      closedOn: '2026-09-20',
      note: 'Client highly satisfied. Repeat work for adjoining iron ore block expected next quarter.',
    },
    submission: {
      mode: 'IBM online portal',
      ackNo: 'IBM/BLR/2025/1190/ACK',
      date: '2026-05-15',
      by: 'N. Rathore',
      files: [],
    },
    documents: [
      { id: 'doc-51', name: 'IBM_Approved_Mining_Plan_Certificate.pdf', size: 5400000, type: 'application/pdf', category: 'Report', addedOn: '2026-08-10', shared: true },
    ],
    history: [
      { id: 'h-51', kind: 'created', date: '2025-11-01', text: 'Project created — work confirmed by JSW Steel Mining' },
      { id: 'h-52', kind: 'submission', date: '2026-05-15', text: 'Submitted to Indian Bureau of Mines via IBM online portal · Ack. IBM/BLR/2025/1190/ACK' },
      { id: 'h-53', kind: 'letter', date: '2026-08-10', text: 'Letter received: Mining Plan Formal Approval Letter (IBM/BLR/MP/2026/4921)' },
      { id: 'h-54', kind: 'closure', date: '2026-09-20', text: 'Final report and approval handed over, payment received, files archived' },
      { id: 'h-55', kind: 'closed', date: '2026-09-20', text: 'Project closed — Indian Bureau of Mines approval received. Client highly satisfied.' },
    ],
    now: { label: 'Project closed', date: '2026-09-20' },
  },
];
