import {
  Employee,
  AttendanceRecord,
  LeaveBalance,
  LeaveRequest,
  ExpenseClaim,
  ExpenseQuery,
  ReimbursementClaim,
  SalaryStructure,
  Payslip,
  PayrollRun,
  Department,
  Designation,
  Shift,
  ShiftAssignment,
  RosterEntry,
  PerformanceAppraisal,
  EmployeeExitRequest,
  HrDocument,
  EmployeeDocumentRecord,
} from '../../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeId: 'BGS-2021-001',
    name: 'Dr. Rajesh Bansal',
    email: 'rajesh.bansal@bansalgeo.com',
    phone: '9829010001',
    role: 'hr',
    employment: {
      department: 'Executive Board',
      designation: 'Managing Director & Chief Geoscientist',
      status: 'Active',
      joiningDate: '2021-04-01',
      workLocation: 'Jaipur HQ',
    },
    kyc: {
      panNumber: 'AAAPL1234F',
      aadhaarNumber: 'XXXX-XXXX-1122',
      bankAccount: '912010045678901',
      ifscCode: 'HDFC0000123',
    },
  },
  {
    id: 'emp-002',
    employeeId: 'BGS-2021-009',
    name: 'Pooja Joshi',
    email: 'pooja.joshi@bansalgeo.com',
    phone: '9829010009',
    role: 'hr',
    employment: {
      department: 'Human Resources',
      designation: 'Head of Human Resources',
      status: 'Active',
      joiningDate: '2021-07-15',
      workLocation: 'Jaipur HQ',
    },
    kyc: {
      panNumber: 'BPPJ9876K',
      aadhaarNumber: 'XXXX-XXXX-3344',
      bankAccount: '912010045678909',
      ifscCode: 'ICIC0000456',
    },
  },
  {
    id: 'emp-003',
    employeeId: 'BGS-2022-011',
    name: 'Ramesh Iyer',
    email: 'ramesh.iyer@bansalgeo.com',
    phone: '9829010011',
    role: 'employee',
    employment: {
      department: 'Finance & Accounts',
      designation: 'Chief Financial Controller',
      status: 'Active',
      joiningDate: '2022-01-10',
      workLocation: 'Jaipur HQ',
    },
    kyc: {
      panNumber: 'AIYPR1122D',
      aadhaarNumber: 'XXXX-XXXX-5566',
      bankAccount: '912010045678911',
      ifscCode: 'SBIN0000789',
    },
  },
  {
    id: 'emp-004',
    employeeId: 'BGS-2022-018',
    name: 'Vikram Patel',
    email: 'vikram.patel@bansalgeo.com',
    phone: '9829010018',
    role: 'employee',
    employment: {
      department: 'Geology & Mineral Exploration',
      designation: 'Chief Geophysical Project Manager',
      status: 'Active',
      joiningDate: '2022-06-01',
      workLocation: 'Field Deployment',
    },
    kyc: {
      panNumber: 'APTLV3344P',
      aadhaarNumber: 'XXXX-XXXX-7788',
      bankAccount: '912010045678918',
      ifscCode: 'HDFC0000123',
    },
  },
  {
    id: 'emp-005',
    employeeId: 'BGS-2023-044',
    name: 'Neha Gupta',
    email: 'neha.gupta@bansalgeo.com',
    phone: '9829010044',
    role: 'employee',
    employment: {
      department: 'Geology & Mineral Exploration',
      designation: 'Field Exploration Geologist',
      status: 'Active',
      joiningDate: '2023-08-15',
      workLocation: 'Bhilwara Site Camp',
    },
    kyc: {
      panNumber: 'BNHGP5566Q',
      aadhaarNumber: 'XXXX-XXXX-9900',
      bankAccount: '912010045678944',
      ifscCode: 'KKBK0000123',
    },
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Rajesh Bansal',
    date: '2026-10-02',
    status: 'Present',
    punchIn: '09:05 AM',
    punchOut: '-',
    durationHours: 4.5,
    workLocation: 'Jaipur HQ',
    coordinates: { latitude: 26.9124, longitude: 75.7873 },
  },
  {
    id: 'att-2',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    date: '2026-10-02',
    status: 'Field Duty',
    punchIn: '08:30 AM',
    punchOut: '-',
    durationHours: 5.1,
    workLocation: 'Bhilwara Rig #3',
    coordinates: { latitude: 25.3476, longitude: 74.6408 },
  },
];

export const INITIAL_LEAVE_BALANCES: Record<string, LeaveBalance[]> = {
  'BGS-2021-001': [
    { id: 'bal-BGS-2021-001-CL', leaveType: 'Casual Leave (CL)', totalAllocated: 12, allocated: 12, used: 2, pending: 0, available: 10, color: '#3B82F6', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal' },
    { id: 'bal-BGS-2021-001-SL', leaveType: 'Sick Leave (SL)', totalAllocated: 10, allocated: 10, used: 0, pending: 0, available: 10, color: '#10B981', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal' },
    { id: 'bal-BGS-2021-001-EL', leaveType: 'Earned / Privilege Leave (EL)', totalAllocated: 18, allocated: 18, used: 4, pending: 0, available: 14, color: '#F59E0B', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal' },
    { id: 'bal-BGS-2021-001-CO', leaveType: 'Compensatory Off (CO)', totalAllocated: 8, allocated: 8, used: 0, pending: 0, available: 8, color: '#8B5CF6', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal' },
    { id: 'bal-BGS-2021-001-FDL', leaveType: 'Field Duty Leave (FDL)', totalAllocated: 15, allocated: 15, used: 3, pending: 0, available: 12, color: '#06B6D4', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal' },
    { id: 'bal-BGS-2021-001-ML', leaveType: 'Maternity / Paternity Leave', totalAllocated: 180, allocated: 180, used: 0, pending: 0, available: 180, color: '#EC4899', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal' },
  ],
  'BGS-2021-009': [
    { id: 'bal-BGS-2021-009-CL', leaveType: 'Casual Leave (CL)', totalAllocated: 12, allocated: 12, used: 1, pending: 0, available: 11, color: '#3B82F6', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi' },
    { id: 'bal-BGS-2021-009-SL', leaveType: 'Sick Leave (SL)', totalAllocated: 10, allocated: 10, used: 1, pending: 0, available: 9, color: '#10B981', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi' },
    { id: 'bal-BGS-2021-009-EL', leaveType: 'Earned / Privilege Leave (EL)', totalAllocated: 18, allocated: 18, used: 3, pending: 0, available: 15, color: '#F59E0B', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi' },
    { id: 'bal-BGS-2021-009-CO', leaveType: 'Compensatory Off (CO)', totalAllocated: 8, allocated: 8, used: 0, pending: 0, available: 8, color: '#8B5CF6', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi' },
    { id: 'bal-BGS-2021-009-FDL', leaveType: 'Field Duty Leave (FDL)', totalAllocated: 15, allocated: 15, used: 0, pending: 0, available: 15, color: '#06B6D4', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi' },
    { id: 'bal-BGS-2021-009-ML', leaveType: 'Maternity / Paternity Leave', totalAllocated: 180, allocated: 180, used: 0, pending: 0, available: 180, color: '#EC4899', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi' },
  ],
  'BGS-2022-011': [
    { id: 'bal-BGS-2022-011-CL', leaveType: 'Casual Leave (CL)', totalAllocated: 12, allocated: 12, used: 3, pending: 0, available: 9, color: '#3B82F6', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer' },
    { id: 'bal-BGS-2022-011-SL', leaveType: 'Sick Leave (SL)', totalAllocated: 10, allocated: 10, used: 0, pending: 0, available: 10, color: '#10B981', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer' },
    { id: 'bal-BGS-2022-011-EL', leaveType: 'Earned / Privilege Leave (EL)', totalAllocated: 18, allocated: 18, used: 5, pending: 0, available: 13, color: '#F59E0B', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer' },
    { id: 'bal-BGS-2022-011-CO', leaveType: 'Compensatory Off (CO)', totalAllocated: 8, allocated: 8, used: 1, pending: 0, available: 7, color: '#8B5CF6', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer' },
    { id: 'bal-BGS-2022-011-FDL', leaveType: 'Field Duty Leave (FDL)', totalAllocated: 15, allocated: 15, used: 0, pending: 0, available: 15, color: '#06B6D4', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer' },
    { id: 'bal-BGS-2022-011-ML', leaveType: 'Maternity / Paternity Leave', totalAllocated: 180, allocated: 180, used: 0, pending: 0, available: 180, color: '#EC4899', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer' },
  ],
  'BGS-2022-018': [
    { id: 'bal-BGS-2022-018-CL', leaveType: 'Casual Leave (CL)', totalAllocated: 12, allocated: 12, used: 2, pending: 0, available: 10, color: '#3B82F6', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel' },
    { id: 'bal-BGS-2022-018-SL', leaveType: 'Sick Leave (SL)', totalAllocated: 10, allocated: 10, used: 1, pending: 0, available: 9, color: '#10B981', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel' },
    { id: 'bal-BGS-2022-018-EL', leaveType: 'Earned / Privilege Leave (EL)', totalAllocated: 18, allocated: 18, used: 4, pending: 0, available: 14, color: '#F59E0B', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel' },
    { id: 'bal-BGS-2022-018-CO', leaveType: 'Compensatory Off (CO)', totalAllocated: 8, allocated: 8, used: 2, pending: 0, available: 6, color: '#8B5CF6', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel' },
    { id: 'bal-BGS-2022-018-FDL', leaveType: 'Field Duty Leave (FDL)', totalAllocated: 15, allocated: 15, used: 6, pending: 0, available: 9, color: '#06B6D4', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel' },
    { id: 'bal-BGS-2022-018-ML', leaveType: 'Maternity / Paternity Leave', totalAllocated: 180, allocated: 180, used: 0, pending: 0, available: 180, color: '#EC4899', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel' },
  ],
  'BGS-2023-044': [
    { id: 'bal-BGS-2023-044-CL', leaveType: 'Casual Leave (CL)', totalAllocated: 12, allocated: 12, used: 1, pending: 3, available: 11, color: '#3B82F6', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta' },
    { id: 'bal-BGS-2023-044-SL', leaveType: 'Sick Leave (SL)', totalAllocated: 10, allocated: 10, used: 2, pending: 0, available: 8, color: '#10B981', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta' },
    { id: 'bal-BGS-2023-044-EL', leaveType: 'Earned / Privilege Leave (EL)', totalAllocated: 18, allocated: 18, used: 0, pending: 0, available: 18, color: '#F59E0B', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta' },
    { id: 'bal-BGS-2023-044-CO', leaveType: 'Compensatory Off (CO)', totalAllocated: 8, allocated: 8, used: 1, pending: 0, available: 7, color: '#8B5CF6', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta' },
    { id: 'bal-BGS-2023-044-FDL', leaveType: 'Field Duty Leave (FDL)', totalAllocated: 15, allocated: 15, used: 5, pending: 0, available: 10, color: '#06B6D4', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta' },
    { id: 'bal-BGS-2023-044-ML', leaveType: 'Maternity / Paternity Leave', totalAllocated: 180, allocated: 180, used: 0, pending: 0, available: 180, color: '#EC4899', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta' },
  ],
};

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lr-501',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Geology & Mineral Exploration',
    leaveType: 'Casual Leave (CL)',
    startDate: '2026-09-18',
    endDate: '2026-09-19',
    days: 2,
    requestedDays: 2,
    approvedDays: 2,
    rejectedDays: 0,
    reason: 'Family function and personal event in Dausa district.',
    contactDuringLeave: '+91 98290 10018',
    status: 'Approved',
    appliedAt: '2026-09-16',
    appliedOn: '2026-09-16',
    reviewedAt: '2026-09-16T11:30:00.000Z',
    approverName: 'Dr. Rajesh Bansal',
    approverComment: 'Approved. Enjoy the family event.',
  },
  {
    id: 'lr-502',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    leaveType: 'Casual Leave (CL)',
    startDate: '2026-10-12',
    endDate: '2026-10-14',
    days: 3,
    requestedDays: 3,
    approvedDays: 0,
    rejectedDays: 0,
    reason: 'Attending sibling wedding ceremony in Delhi NCR.',
    contactDuringLeave: '+91 98290 10044',
    status: 'Pending',
    appliedAt: '2026-10-01',
    appliedOn: '2026-10-01',
  },
  {
    id: 'lr-503',
    employeeId: 'BGS-2022-011',
    employeeName: 'Ramesh Iyer',
    department: 'Finance & Accounts',
    leaveType: 'Sick Leave (SL)',
    startDate: '2026-09-21',
    endDate: '2026-09-22',
    days: 2,
    requestedDays: 2,
    approvedDays: 2,
    rejectedDays: 0,
    reason: 'Acute viral fever and medical consultation rest.',
    contactDuringLeave: '+91 98290 10011',
    status: 'Approved',
    appliedAt: '2026-09-20',
    appliedOn: '2026-09-20',
    reviewedAt: '2026-09-20T16:00:00.000Z',
    approverName: 'Pooja Joshi',
    approverComment: 'Approved. Take medical rest and recover.',
  },
  {
    id: 'lr-504',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    leaveType: 'Sick Leave (SL)',
    startDate: '2026-08-24',
    endDate: '2026-08-25',
    days: 2,
    requestedDays: 2,
    approvedDays: 2,
    rejectedDays: 0,
    reason: 'Severe migraine attack and ophthalmologist checkup.',
    contactDuringLeave: '+91 98290 10044',
    status: 'Approved',
    appliedAt: '2026-08-23',
    appliedOn: '2026-08-23',
    reviewedAt: '2026-08-23T18:00:00.000Z',
    approverName: 'Pooja Joshi',
    approverComment: 'Approved with medical slip.',
  },
  {
    id: 'lr-505',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Geology & Mineral Exploration',
    leaveType: 'Field Duty Leave (FDL)',
    startDate: '2026-08-10',
    endDate: '2026-08-14',
    days: 5,
    requestedDays: 5,
    approvedDays: 5,
    rejectedDays: 0,
    reason: 'Rest and recuperation post 30-day drilling campaign at Bhilwara belt.',
    contactDuringLeave: '+91 98290 10018',
    status: 'Approved',
    appliedAt: '2026-08-01',
    appliedOn: '2026-08-01',
    reviewedAt: '2026-08-02T10:15:00.000Z',
    approverName: 'Pooja Joshi',
    approverComment: 'Approved. Well-earned recuperation following field tour completion.',
  },
  {
    id: 'lr-506',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Rajesh Bansal',
    department: 'Executive Board',
    leaveType: 'Earned / Privilege Leave (EL)',
    startDate: '2026-10-26',
    endDate: '2026-10-29',
    days: 4,
    requestedDays: 4,
    approvedDays: 0,
    rejectedDays: 0,
    reason: 'Annual family festival visit and regional symposium keynote.',
    contactDuringLeave: '+91 98290 10001',
    status: 'Pending',
    appliedAt: '2026-09-28',
    appliedOn: '2026-09-28',
  },
  {
    id: 'lr-507',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Geology & Mineral Exploration',
    leaveType: 'Casual Leave (CL)',
    startDate: '2026-07-06',
    endDate: '2026-07-08',
    days: 3,
    requestedDays: 3,
    approvedDays: 0,
    rejectedDays: 3,
    reason: 'Short vacation with family.',
    contactDuringLeave: '+91 98290 10018',
    status: 'Rejected',
    rejectionReason: 'Critical site mobilization audit scheduled during this period. Please reschedule to next sprint.',
    appliedAt: '2026-07-01',
    appliedOn: '2026-07-01',
    reviewedAt: '2026-07-02T12:00:00.000Z',
    approverName: 'Dr. Rajesh Bansal',
    approverComment: 'Critical site mobilization audit scheduled during this period. Please reschedule to next sprint.',
  },
];

export const INITIAL_EXPENSES: ExpenseClaim[] = [
  {
    id: 'exp-001',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    category: 'Field Supplies',
    requestedAmount: 4800,
    approvedAmount: 4800,
    rejectedAmount: 0,
    settledAmount: 0,
    date: '2026-09-24',
    project: 'Bhilwara Lead-Zinc Exploration Block',
    description: 'Emergency core sample boxes & water-resistant marking pens for BH-07 logging.',
    status: 'Approved',
    receiptFileName: 'core_boxes_invoice_receipt.jpg',
  },
  {
    id: 'exp-002',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Geology & Mineral Exploration',
    category: 'Travel & Conveyance',
    requestedAmount: 12000,
    approvedAmount: 9000,
    rejectedAmount: 3000,
    settledAmount: 9000,
    date: '2026-09-18',
    project: 'Sukinda Chromite Geotechnical Study',
    description: 'Vehicle hire for exploratory field reconnaissance in Sukinda Valley.',
    status: 'Settled',
    receiptFileName: 'taxi_hire_voucher.jpg',
    settlementReference: 'DISB-2026-0918',
    settlementDate: '2026-09-21',
  },
];

export const INITIAL_QUERIES: ExpenseQuery[] = [];

export const INITIAL_REIMBURSEMENTS: ReimbursementClaim[] = [
  {
    id: 'reimb-001',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    category: 'Vehicle Mileage',
    claimAmount: 3200,
    approvedAmount: 3200,
    rejectedAmount: 0,
    settledAmount: 3200,
    date: '2026-09-22',
    kilometersDriven: 400,
    ratePerKm: 8,
    remarks: 'Field site commute between Bhilwara base camp and drill rig sites.',
    status: 'Settled',
    settlementReference: 'DISB-2026-0923',
  },
];

export const INITIAL_SALARY_STRUCTURES: SalaryStructure[] = [
  {
    id: 'sal-1',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Rajesh Bansal',
    designation: 'Managing Director & Chief Geoscientist',
    department: 'Executive Board',
    annualCtc: 3600000,
    monthlyGross: 300000,
    basic: 120000,
    hra: 60000,
    conveyance: 15000,
    specialAllowance: 75000,
    siteAllowance: 30000,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 35000,
    monthlyNet: 263000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'sal-2',
    employeeId: 'BGS-2021-009',
    employeeName: 'Pooja Joshi',
    designation: 'Head of Human Resources',
    department: 'Human Resources',
    annualCtc: 1800000,
    monthlyGross: 150000,
    basic: 60000,
    hra: 30000,
    conveyance: 8000,
    specialAllowance: 42000,
    siteAllowance: 10000,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 14000,
    monthlyNet: 134000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'sal-3',
    employeeId: 'BGS-2022-011',
    employeeName: 'Ramesh Iyer',
    designation: 'Finance Controller',
    department: 'Finance & Accounts',
    annualCtc: 2400000,
    monthlyGross: 200000,
    basic: 80000,
    hra: 40000,
    conveyance: 10000,
    specialAllowance: 50000,
    siteAllowance: 20000,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 21000,
    monthlyNet: 177000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'sal-4',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    designation: 'Lead Geologist',
    department: 'Mining Services',
    annualCtc: 1380000,
    monthlyGross: 115000,
    basic: 55000,
    hra: 22000,
    conveyance: 5000,
    specialAllowance: 33000,
    siteAllowance: 0,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 7000,
    monthlyNet: 106000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'sal-5',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    designation: 'GIS Analyst',
    department: 'GIS & Remote Sensing',
    annualCtc: 780000,
    monthlyGross: 65000,
    basic: 30000,
    hra: 12000,
    conveyance: 5000,
    specialAllowance: 18000,
    siteAllowance: 0,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 4000,
    monthlyNet: 59000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'sal-bgs-001',
    employeeId: 'BGS-001',
    employeeName: 'Dr. Amit Kumar Bansal',
    designation: 'Managing Director & Chief Geologist',
    department: 'Geology & Mineral Exploration',
    annualCtc: 3600000,
    monthlyGross: 300000,
    basic: 120000,
    hra: 60000,
    conveyance: 15000,
    specialAllowance: 75000,
    siteAllowance: 30000,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 35000,
    monthlyNet: 263000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'sal-bgs-003',
    employeeId: 'BGS-003',
    employeeName: 'Rajesh Sharma',
    designation: 'Principal Mining Consultant',
    department: 'Mining & Mine Planning',
    annualCtc: 2400000,
    monthlyGross: 200000,
    basic: 80000,
    hra: 40000,
    conveyance: 10000,
    specialAllowance: 50000,
    siteAllowance: 20000,
    providentFund: 1800,
    epf: 1800,
    professionalTax: 200,
    pt: 200,
    esi: 0,
    tds: 21000,
    monthlyNet: 177000,
    effectiveDate: '2026-04-01',
    status: 'Active',
  },
];

export const INITIAL_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-2026-08-001',
    payslipNumber: 'BGS/PAY/2026/08/001',
    payslipNo: 'BGS/PAY/2026/08/001',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Rajesh Bansal',
    department: 'Executive Board',
    designation: 'Managing Director & Chief Geoscientist',
    joiningDate: '2021-04-01',
    pan: 'AAAPL1234F',
    uan: '100923847291',
    bankName: 'HDFC Bank Ltd.',
    accountNumber: '•••• •••• 8901',
    month: 'August 2026',
    monthKey: '2026-08',
    year: 2026,
    workingDays: 31,
    paidDays: 31,
    payableDays: 31,
    lopDays: 0,
    basic: 120000,
    hra: 60000,
    conveyance: 15000,
    specialAllowance: 75000,
    siteAllowance: 30000,
    bonus: 0,
    grossEarnings: 300000,
    providentFund: 1800,
    epfDeduction: 1800,
    professionalTax: 200,
    ptDeduction: 200,
    esi: 0,
    esiDeduction: 0,
    tds: 35000,
    tdsDeduction: 35000,
    otherDeductions: 0,
    totalDeductions: 37000,
    netSalary: 263000,
    netTakeHome: 263000,
    netSalaryInWords: 'Two Lakh Sixty Three Thousand Rupees Only',
    paymentStatus: 'Paid',
    paymentDate: '2026-08-31',
    transactionRef: 'NEFT-HDFC-982187361',
  },
  {
    id: 'ps-2026-08-002',
    payslipNumber: 'BGS/PAY/2026/08/002',
    payslipNo: 'BGS/PAY/2026/08/002',
    employeeId: 'BGS-2021-009',
    employeeName: 'Pooja Joshi',
    department: 'Human Resources',
    designation: 'Head of Human Resources',
    joiningDate: '2021-06-15',
    pan: 'BBBPJ5678K',
    uan: '100847291039',
    bankName: 'ICICI Bank Ltd.',
    accountNumber: '•••• •••• 4512',
    month: 'August 2026',
    monthKey: '2026-08',
    year: 2026,
    workingDays: 31,
    paidDays: 31,
    payableDays: 31,
    lopDays: 0,
    basic: 60000,
    hra: 30000,
    conveyance: 8000,
    specialAllowance: 42000,
    siteAllowance: 10000,
    bonus: 0,
    grossEarnings: 150000,
    providentFund: 1800,
    epfDeduction: 1800,
    professionalTax: 200,
    ptDeduction: 200,
    esi: 0,
    esiDeduction: 0,
    tds: 14000,
    tdsDeduction: 14000,
    otherDeductions: 0,
    totalDeductions: 16000,
    netSalary: 134000,
    netTakeHome: 134000,
    netSalaryInWords: 'One Lakh Thirty Four Thousand Rupees Only',
    paymentStatus: 'Paid',
    paymentDate: '2026-08-31',
    transactionRef: 'NEFT-ICICI-662819203',
  },
  {
    id: 'ps-2026-08-003',
    payslipNumber: 'BGS/PAY/2026/08/003',
    payslipNo: 'BGS/PAY/2026/08/003',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Mining Services',
    designation: 'Lead Geologist',
    joiningDate: '2022-08-01',
    pan: 'CCCSH9012L',
    uan: '100456789123',
    bankName: 'State Bank of India',
    accountNumber: '•••• •••• 5612',
    month: 'August 2026',
    monthKey: '2026-08',
    year: 2026,
    workingDays: 31,
    paidDays: 31,
    payableDays: 31,
    lopDays: 0,
    basic: 55000,
    hra: 22000,
    conveyance: 5000,
    specialAllowance: 33000,
    siteAllowance: 0,
    bonus: 0,
    grossEarnings: 115000,
    providentFund: 1800,
    epfDeduction: 1800,
    professionalTax: 200,
    ptDeduction: 200,
    esi: 0,
    esiDeduction: 0,
    tds: 7000,
    tdsDeduction: 7000,
    otherDeductions: 0,
    totalDeductions: 9000,
    netSalary: 106000,
    netTakeHome: 106000,
    netSalaryInWords: 'One Lakh Six Thousand Rupees Only',
    paymentStatus: 'Paid',
    paymentDate: '2026-08-31',
    transactionRef: 'NEFT-SBI-451928371',
  },
  {
    id: 'ps-2026-08-004',
    payslipNumber: 'BGS/PAY/2026/08/004',
    payslipNo: 'BGS/PAY/2026/08/004',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'GIS & Remote Sensing',
    designation: 'GIS Analyst',
    joiningDate: '2023-03-01',
    pan: 'GGGCW9988Q',
    uan: '100876543210',
    bankName: 'State Bank of India',
    accountNumber: '•••• •••• 7103',
    month: 'August 2026',
    monthKey: '2026-08',
    year: 2026,
    workingDays: 31,
    paidDays: 31,
    payableDays: 31,
    lopDays: 0,
    basic: 30000,
    hra: 12000,
    conveyance: 5000,
    specialAllowance: 18000,
    siteAllowance: 0,
    bonus: 0,
    grossEarnings: 65000,
    providentFund: 1800,
    epfDeduction: 1800,
    professionalTax: 200,
    ptDeduction: 200,
    esi: 0,
    esiDeduction: 0,
    tds: 4000,
    tdsDeduction: 4000,
    otherDeductions: 0,
    totalDeductions: 6000,
    netSalary: 59000,
    netTakeHome: 59000,
    netSalaryInWords: 'Fifty Nine Thousand Rupees Only',
    paymentStatus: 'Paid',
    paymentDate: '2026-08-31',
    transactionRef: 'NEFT-SBI-881920391',
  },
];

export const INITIAL_PAYROLL_RUNS: PayrollRun[] = [
  {
    id: 'pr-2026-08',
    month: 'August 2026',
    monthKey: '2026-08',
    processedDate: '2026-08-31',
    totalEmployees: 5,
    totalGross: 830000,
    totalDeductions: 89000,
    totalNetDisbursed: 741000,
    status: 'Completed',
    processedBy: 'Chhavi Bansal (Director - Finance)',
  },
  {
    id: 'pr-2026-07',
    month: 'July 2026',
    monthKey: '2026-07',
    processedDate: '2026-07-31',
    totalEmployees: 5,
    totalGross: 825000,
    totalDeductions: 88500,
    totalNetDisbursed: 736500,
    status: 'Completed',
    processedBy: 'Chhavi Bansal (Director - Finance)',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-geo', code: 'GEO', name: 'Geology & Mineral Exploration', headName: 'Dr. Amit Kumar Bansal', headEmployeeId: 'BGS-001', staffCount: 18, employeeCount: 18, location: 'Jaipur Corporate HQ & Field Sites', description: 'Exploration program design, core logging, 3D modeling and resource estimation.', status: 'Active' },
  { id: 'dept-mine', code: 'MINE', name: 'Mining & Mine Planning', headName: 'Rajesh Sharma', headEmployeeId: 'BGS-003', staffCount: 14, employeeCount: 14, location: 'Jaipur HQ & Bhilwara Mine Site', description: 'Bankable mine feasibility studies, open-pit & underground design, production scheduling.', status: 'Active' },
  { id: 'dept-gis', code: 'GIS', name: 'GIS, Remote Sensing & UAV', headName: 'Vikramaditya Rathore', headEmployeeId: 'BGS-005', staffCount: 12, employeeCount: 12, location: 'Jaipur Corporate HQ', description: 'High-resolution drone aerial mapping, hyperspectral remote sensing, DEM creation.', status: 'Active' },
  { id: 'dept-hydro', code: 'HYDRO', name: 'Hydrogeology & Groundwater', headName: 'Dr. Sunita Meena', headEmployeeId: 'BGS-008', staffCount: 8, employeeCount: 8, location: 'Jaipur HQ & Udaipur Site', description: 'Aquifer numerical modeling, mine pit dewatering system design, groundwater monitoring.', status: 'Active' },
  { id: 'dept-env', code: 'ENV', name: 'Environment & Permitting', headName: 'Dr. Ananya Joshi', headEmployeeId: 'BGS-011', staffCount: 9, employeeCount: 9, location: 'Jaipur Corporate HQ', description: 'EIA/EMP studies, environmental clearances, forest clearance compliance, mine closure.', status: 'Active' },
  { id: 'dept-geotech', code: 'GEOTECH', name: 'Geotechnical Engineering', headName: 'Mohammad Farooq', headEmployeeId: 'BGS-014', staffCount: 7, employeeCount: 7, location: 'Bhilwara Site Office', description: 'Rock mass characterization, slope stability analysis, tailings dam engineering.', status: 'Active' },
  { id: 'dept-fin', code: 'FIN', name: 'Finance & Mineral Economics', headName: 'Chhavi Bansal', headEmployeeId: 'BGS-002', staffCount: 8, employeeCount: 8, location: 'Jaipur Corporate HQ', description: 'Project financial modeling, mineral asset valuation, taxation, payroll accounting.', status: 'Active' },
  { id: 'dept-hr', code: 'HR', name: 'Human Resources & Admin', headName: 'Kritika Gupta', headEmployeeId: 'BGS-004', staffCount: 6, employeeCount: 6, location: 'Jaipur Corporate HQ', description: 'Talent acquisition, field safety training, payroll administration, statutory compliance.', status: 'Active' },
  { id: 'dept-it', code: 'IT', name: 'Information Technology', headName: 'Alok Verma', headEmployeeId: 'BGS-017', staffCount: 5, employeeCount: 5, location: 'Jaipur Corporate HQ', description: 'Geospatial servers, cloud infrastructure, geological software licensing and HRMS.', status: 'Active' },
];

export const INITIAL_DESIGNATIONS: Designation[] = [
  { id: 'desig-1', title: 'Managing Director & Chief Geologist', code: 'MD-GEO', departmentId: 'dept-geo', departmentName: 'Geology & Mineral Exploration', department: 'Geology & Mineral Exploration', grade: 'L6', level: 'L6', assignedStaffCount: 1, employeeCount: 1, minExperience: '15+ Years', status: 'Active' },
  { id: 'desig-2', title: 'Director - Finance & Strategy', code: 'DIR-FIN', departmentId: 'dept-fin', departmentName: 'Finance & Mineral Economics', department: 'Finance & Mineral Economics', grade: 'L6', level: 'L6', assignedStaffCount: 1, employeeCount: 1, minExperience: '12+ Years', status: 'Active' },
  { id: 'desig-3', title: 'Principal Mining Consultant', code: 'PR-MINE', departmentId: 'dept-mine', departmentName: 'Mining & Mine Planning', department: 'Mining & Mine Planning', grade: 'L5', level: 'L5', assignedStaffCount: 1, employeeCount: 1, minExperience: '10+ Years', status: 'Active' },
  { id: 'desig-4', title: 'Lead GIS & Remote Sensing Specialist', code: 'LD-GIS', departmentId: 'dept-gis', departmentName: 'GIS, Remote Sensing & UAV', department: 'GIS, Remote Sensing & UAV', grade: 'L5', level: 'L5', assignedStaffCount: 1, employeeCount: 1, minExperience: '8+ Years', status: 'Active' },
  { id: 'desig-5', title: 'Head - HR & Administration', code: 'HD-HR', departmentId: 'dept-hr', departmentName: 'Human Resources & Admin', department: 'Human Resources & Admin', grade: 'L5', level: 'L5', assignedStaffCount: 1, employeeCount: 1, minExperience: '8+ Years', status: 'Active' },
  { id: 'desig-6', title: 'Senior Exploration Geologist', code: 'SR-GEO', departmentId: 'dept-geo', departmentName: 'Geology & Mineral Exploration', department: 'Geology & Mineral Exploration', grade: 'L4', level: 'L4', assignedStaffCount: 1, employeeCount: 1, minExperience: '5-8 Years', status: 'Active' },
  { id: 'desig-7', title: 'Senior Hydrogeologist', code: 'SR-HYDRO', departmentId: 'dept-hydro', departmentName: 'Hydrogeology & Groundwater', department: 'Hydrogeology & Groundwater', grade: 'L4', level: 'L4', assignedStaffCount: 1, employeeCount: 1, minExperience: '5-8 Years', status: 'Active' },
  { id: 'desig-8', title: 'Senior Mine Planning Engineer', code: 'SR-MINE', departmentId: 'dept-mine', departmentName: 'Mining & Mine Planning', department: 'Mining & Mine Planning', grade: 'L4', level: 'L4', assignedStaffCount: 0, employeeCount: 0, minExperience: '5-8 Years', status: 'Active' },
  { id: 'desig-9', title: 'Senior Geotechnical Engineer', code: 'SR-GEOTECH', departmentId: 'dept-geotech', departmentName: 'Geotechnical Engineering', department: 'Geotechnical Engineering', grade: 'L4', level: 'L4', assignedStaffCount: 0, employeeCount: 0, minExperience: '5-8 Years', status: 'Active' },
  { id: 'desig-10', title: 'Environmental Compliance Officer', code: 'ENV-OFF', departmentId: 'dept-env', departmentName: 'Environment & Permitting', department: 'Environment & Permitting', grade: 'L3', level: 'L3', assignedStaffCount: 0, employeeCount: 0, minExperience: '3-5 Years', status: 'Active' },
  { id: 'desig-11', title: 'UAV / Drone Survey Pilot & Analyst', code: 'UAV-PLT', departmentId: 'dept-gis', departmentName: 'GIS, Remote Sensing & UAV', department: 'GIS, Remote Sensing & UAV', grade: 'L3', level: 'L3', assignedStaffCount: 1, employeeCount: 1, minExperience: '3-5 Years', status: 'Active' },
  { id: 'desig-12', title: 'Field Geologist', code: 'FLD-GEO', departmentId: 'dept-geo', departmentName: 'Geology & Mineral Exploration', department: 'Geology & Mineral Exploration', grade: 'L2', level: 'L2', assignedStaffCount: 1, employeeCount: 1, minExperience: '1-3 Years', status: 'Active' },
  { id: 'desig-13', title: 'Junior GIS Analyst', code: 'JR-GIS', departmentId: 'dept-gis', departmentName: 'GIS, Remote Sensing & UAV', department: 'GIS, Remote Sensing & UAV', grade: 'L2', level: 'L2', assignedStaffCount: 0, employeeCount: 0, minExperience: '1-3 Years', status: 'Active' },
  { id: 'desig-14', title: 'HR Executive', code: 'HR-EXEC', departmentId: 'dept-hr', departmentName: 'Human Resources & Admin', department: 'Human Resources & Admin', grade: 'L2', level: 'L2', assignedStaffCount: 1, employeeCount: 1, minExperience: '2-4 Years', status: 'Active' },
  { id: 'desig-15', title: 'Accountant & Payroll Executive', code: 'ACC-EXEC', departmentId: 'dept-fin', departmentName: 'Finance & Mineral Economics', department: 'Finance & Mineral Economics', grade: 'L2', level: 'L2', assignedStaffCount: 0, employeeCount: 0, minExperience: '2-4 Years', status: 'Active' },
  { id: 'desig-16', title: 'Systems & Network Engineer', code: 'SYS-ENG', departmentId: 'dept-it', departmentName: 'Information Technology', department: 'Information Technology', grade: 'L3', level: 'L3', assignedStaffCount: 0, employeeCount: 0, minExperience: '3-5 Years', status: 'Active' },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'sh-1',
    name: 'General Corporate Shift (HQ)',
    code: 'HQ-GEN',
    startTime: '09:30 AM',
    endTime: '06:00 PM',
    workHours: 8.5,
    breakDuration: '45 mins',
    gracePeriod: '15 mins',
    weeklyOff: 'Saturday & Sunday',
    location: 'Jaipur Corporate HQ',
    status: 'Active',
    assignedEmployeesCount: 48,
    description: 'Standard office hours for Corporate Management, HR, Finance, and GIS modeling teams.',
  },
  {
    id: 'sh-2',
    name: 'Mining Site Morning Shift',
    code: 'MINE-MORN',
    startTime: '06:00 AM',
    endTime: '02:30 PM',
    workHours: 8.5,
    breakDuration: '30 mins',
    gracePeriod: '10 mins',
    weeklyOff: 'Sunday',
    location: 'Bhilwara & Udaipur Mine Sites',
    status: 'Active',
    assignedEmployeesCount: 16,
    description: 'Operational shift for blast monitoring, open-pit face mapping, and morning haulage surveys.',
  },
  {
    id: 'sh-3',
    name: 'Mining Site Evening Shift',
    code: 'MINE-EVE',
    startTime: '02:00 PM',
    endTime: '10:30 PM',
    workHours: 8.5,
    breakDuration: '30 mins',
    gracePeriod: '10 mins',
    weeklyOff: 'Sunday',
    location: 'Bhilwara & Udaipur Mine Sites',
    status: 'Active',
    assignedEmployeesCount: 12,
    description: 'Afternoon face inspections, grade control sampling, and geotechnical slope monitoring.',
  },
  {
    id: 'sh-4',
    name: 'Field Survey & Drone Flight Shift',
    code: 'UAV-FLIGHT',
    startTime: '06:30 AM',
    endTime: '03:00 PM',
    workHours: 8.5,
    breakDuration: '45 mins',
    gracePeriod: '15 mins',
    weeklyOff: 'Rotational (1 day / week)',
    location: 'Exploration Blocks / Field',
    status: 'Active',
    assignedEmployeesCount: 10,
    description: 'Early morning daylight flying window for optimal solar angle and minimal thermal atmospheric turbulence.',
  },
];

export const INITIAL_SHIFT_ASSIGNMENTS: ShiftAssignment[] = [
  { id: 'sa-1', employeeId: 'BGS-2021-001', employeeName: 'Dr. Rajesh Bansal', department: 'Executive Board', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-2', employeeId: 'BGS-2021-009', employeeName: 'Pooja Joshi', department: 'Human Resources', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-3', employeeId: 'BGS-2022-011', employeeName: 'Ramesh Iyer', department: 'Finance & Accounts', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-4', employeeId: 'BGS-2022-018', employeeName: 'Vikram Patel', department: 'Geology & Mineral Exploration', shiftId: 'sh-2', shiftName: 'Mining Site Morning Shift', effectiveFrom: '2026-08-01', weeklyOff: 'Sunday', status: 'Active' },
  { id: 'sa-5', employeeId: 'BGS-2023-044', employeeName: 'Neha Gupta', department: 'Geology & Mineral Exploration', shiftId: 'sh-4', shiftName: 'Field Survey & Drone Flight Shift', effectiveFrom: '2026-08-15', weeklyOff: 'Rotational (1 day / week)', status: 'Active' },
  { id: 'sa-6', employeeId: 'BGS-001', employeeName: 'Dr. Amit Kumar Bansal', department: 'Geology & Mineral Exploration', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-7', employeeId: 'BGS-002', employeeName: 'Chhavi Bansal', department: 'Finance & Mineral Economics', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-8', employeeId: 'BGS-003', employeeName: 'Rajesh Sharma', department: 'Mining & Mine Planning', shiftId: 'sh-2', shiftName: 'Mining Site Morning Shift', effectiveFrom: '2026-08-01', weeklyOff: 'Sunday', status: 'Active' },
  { id: 'sa-9', employeeId: 'BGS-004', employeeName: 'Kritika Gupta', department: 'Human Resources & Admin', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-10', employeeId: 'BGS-005', employeeName: 'Vikramaditya Rathore', department: 'GIS, Remote Sensing & UAV', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
  { id: 'sa-11', employeeId: 'BGS-006', employeeName: 'Rohan Deshmukh', department: 'Geology & Mineral Exploration', shiftId: 'sh-2', shiftName: 'Mining Site Morning Shift', effectiveFrom: '2026-08-01', weeklyOff: 'Sunday', status: 'Active' },
  { id: 'sa-12', employeeId: 'BGS-007', employeeName: 'Ravi Gurjar', department: 'GIS, Remote Sensing & UAV', shiftId: 'sh-4', shiftName: 'Field Survey & Drone Flight Shift', effectiveFrom: '2026-08-15', weeklyOff: 'Rotational (1 day / week)', status: 'Active' },
  { id: 'sa-13', employeeId: 'BGS-008', employeeName: 'Dr. Sunita Meena', department: 'Hydrogeology & Groundwater', shiftId: 'sh-1', shiftName: 'General Corporate Shift (HQ)', effectiveFrom: '2026-01-01', weeklyOff: 'Saturday & Sunday', status: 'Active' },
];

export function buildSeededRoster(
  assignments: ShiftAssignment[] = INITIAL_SHIFT_ASSIGNMENTS,
  year: number = 2026,
  month: number = 10
): RosterEntry[] {
  const entries: RosterEntry[] = [];
  const daysInMonth = new Date(year, month, 0).getDate();
  const todayStr = '2026-10-03';

  for (let day = 1; day <= daysInMonth; day++) {
    const dayStr = String(day).padStart(2, '0');
    const monthStr = String(month).padStart(2, '0');
    const dateStr = `${year}-${monthStr}-${dayStr}`;
    const dateObj = new Date(year, month - 1, day);
    const dayOfWeek = dateObj.getDay(); // 0 = Sun, 6 = Sat

    assignments.forEach((asgn) => {
      let isWeeklyOff = false;
      const off = asgn.weeklyOff || 'Sunday';
      if (off === 'Saturday & Sunday') {
        isWeeklyOff = dayOfWeek === 0 || dayOfWeek === 6;
      } else if (off === 'Sunday') {
        isWeeklyOff = dayOfWeek === 0;
      } else if (off.includes('Rotational')) {
        isWeeklyOff = dayOfWeek === 3; // Wednesday rotational off
      }

      let status: RosterEntry['status'];
      if (isWeeklyOff) {
        status = 'Weekly Off';
      } else if (dateStr === todayStr) {
        status = 'Active Today';
      } else if (dateStr < todayStr) {
        status = 'Completed';
      } else {
        status = 'Scheduled';
      }

      entries.push({
        id: `rst-${dateStr}-${asgn.employeeId}`,
        employeeId: asgn.employeeId,
        employeeName: asgn.employeeName,
        department: asgn.department,
        shiftId: asgn.shiftId,
        shiftName: asgn.shiftName,
        date: dateStr,
        status,
        notes: isWeeklyOff ? 'Designated weekly rest day' : `${asgn.shiftName} operational roster`,
      });
    });
  }

  return entries;
}

export const INITIAL_ROSTER: RosterEntry[] = buildSeededRoster();

export const INITIAL_APPRAISALS: PerformanceAppraisal[] = [
  {
    id: 'appr-001',
    employeeId: 'BGS-2022-011',
    employeeName: 'Rohan Deshmukh',
    department: 'Geology & Mineral Exploration',
    designation: 'Senior Exploration Geologist',
    reviewCycle: 'Annual Appraisal FY 2025-26',
    reviewerName: 'Dr. Amit Bansal',
    reviewerDesignation: 'Managing Director',
    overallScore: 4.7,
    goalsAchievementPercent: 94,
    rating: 'Outstanding',
    status: 'HR Finalized',
    reviewDate: '2026-04-15',
    goals: [
      { id: 'g1', title: 'Bhilwara Core Logging & Assay', description: 'Delivered 1,200m drill core characterization within schedule', weightage: 30, targetScore: 5, achievedScore: 4.8 },
      { id: 'g2', title: 'JORC Resource Model Reporting', description: 'Co-authored compliant resource estimation report', weightage: 40, targetScore: 5, achievedScore: 4.7 },
      { id: 'g3', title: 'Site HSE Protocol Adherence', description: 'Zero lost time injuries across field camp assignments', weightage: 30, targetScore: 5, achievedScore: 4.6 },
    ],
    strengths: 'Exceptional structural geology field acumen, fast turnaround on complex mineral core logs, excellent junior mentorship.',
    areasOfImprovement: 'Advanced geostatistical Leapfrog 3D modeling could be further refined with specialized training.',
    managerFeedback: 'Consistently exceptional contributor. Highly recommended for Senior Lead designation & performance bonus.',
    promotionRecommended: true,
    bonusMultiplier: 1.25,
  },
  {
    id: 'appr-002',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Amit Kumar Bansal',
    department: 'Geology & Mineral Exploration',
    designation: 'Managing Director & Chief Geologist',
    reviewCycle: 'Board Review FY 2025-26',
    reviewerName: 'Board of Directors',
    reviewerDesignation: 'Executive Committee',
    overallScore: 4.9,
    goalsAchievementPercent: 98,
    rating: 'Outstanding',
    status: 'HR Finalized',
    reviewDate: '2026-04-20',
    goals: [
      { id: 'g4', title: 'Strategic Revenue & Growth', description: 'Exceeded geological consultancy targets by 22%', weightage: 50, targetScore: 5, achievedScore: 4.9 },
      { id: 'g5', title: 'Highwall Safety Governance', description: 'Zero safety non-conformity across 14 mining concessions', weightage: 50, targetScore: 5, achievedScore: 4.9 },
    ],
    strengths: 'Visionary leadership, technical authority across major mining concessions in Western India.',
    areasOfImprovement: 'Expand international mining symposium presence.',
    managerFeedback: 'Exemplary leadership across corporate governance and geological operations.',
    promotionRecommended: false,
    bonusMultiplier: 1.3,
  },
];

export const INITIAL_EXITS: EmployeeExitRequest[] = [
  {
    id: 'exit-001',
    employeeId: 'BGS-024',
    employeeName: 'Deepak Chouhan',
    department: 'Geology & Mineral Exploration',
    designation: 'Field Geologist',
    exitType: 'Resignation',
    resignationDate: '2026-08-15',
    requestedLWD: '2026-09-15',
    approvedLWD: '2026-09-15',
    noticePeriodDays: 30,
    noticeServedDays: 30,
    reason: 'Higher studies in Geoinformatics abroad (University of Leeds).',
    status: 'In Clearance',
    exitInterviewDone: true,
    exitInterviewFeedback: 'Great field experience, excellent mentorship from Senior Geologist.',
    clearances: [
      { id: 'c1', department: 'IT', reviewerName: 'Aman Jain (Systems Admin)', status: 'Approved', clearanceDate: '2026-09-12', checklistNotes: 'Dell Rugged Latitude laptop and email revoked.' },
      { id: 'c2', department: 'Admin & Assets', reviewerName: 'Dr. Sunita Meena', status: 'Approved', clearanceDate: '2026-09-14', checklistNotes: 'Company ID badge, camp locker key, and safety helmet returned.' },
      { id: 'c3', department: 'Finance & Accounts', reviewerName: 'Dr. Amit Bansal', status: 'Pending', checklistNotes: 'Verifying final site imprest bills (₹4,200 pending submission).', pendingDuesOrAssets: '₹4,200 Imprest voucher adjustment' },
      { id: 'c4', department: 'HR & Legal', reviewerName: 'Kritika Gupta', status: 'Pending', checklistNotes: 'Awaiting finance clearance sign-off to execute F&F statement.' },
    ],
    fnf: {
      id: 'fnf-001',
      exitRequestId: 'exit-001',
      employeeId: 'BGS-024',
      payableDaysSalary: 28500,
      leaveEncashmentAmount: 14250,
      gratuityAmount: 0,
      annualBonusAmount: 5000,
      grossPayable: 47750,
      noticeShortfallDeduction: 0,
      unsettledAdvanceDeduction: 4200,
      taxTdsDeduction: 1200,
      totalDeductions: 5400,
      netPayable: 42350,
      paymentStatus: 'Pending',
    },
    relievingLetterIssued: false,
  },
];

export const INITIAL_HR_DOCUMENTS: HrDocument[] = [
  {
    id: 'cdoc-01',
    title: 'BGSPL Employee Code of Conduct & Ethics 2026',
    category: 'Company Documents',
    fileName: 'BGSPL_Code_Of_Conduct_2026.pdf',
    fileSize: '3.4 MB',
    fileType: 'PDF',
    uploadedBy: 'Kritika Gupta (Head HR)',
    uploadDate: '2026-01-05',
    description: 'Corporate policies on professional ethics, data confidentiality, anti-bribery, and workplace guidelines.',
    accessRole: 'all',
  },
  {
    id: 'cdoc-02',
    title: 'Mining Site Safety Standard Operating Procedures (SOP)',
    category: 'Company Documents',
    fileName: 'BGSPL_Mining_Field_Safety_SOP.pdf',
    fileSize: '5.8 MB',
    fileType: 'PDF',
    uploadedBy: 'Rajesh Sharma (Principal Mining Consultant)',
    uploadDate: '2026-02-10',
    description: 'Mandatory PPE guidelines, open-pit pithead protocols, blast shelter distance, and first-aid procedures.',
    accessRole: 'all',
  },
  {
    id: 'cdoc-03',
    title: 'Drone / UAV DGCA Flight Compliance & Operation Guidelines',
    category: 'Company Documents',
    fileName: 'DGCA_UAV_Flight_Compliance_Handbook.pdf',
    fileSize: '4.2 MB',
    fileType: 'PDF',
    uploadedBy: 'Vikramaditya Rathore',
    uploadDate: '2026-03-12',
    description: 'Guidelines on DigitalSky permissions, NPNT protocols, maximum altitude limits and sensor security.',
    accessRole: 'all',
  },
  {
    id: 'cdoc-04',
    title: 'Annual Performance Appraisal Framework FY 2026-27',
    category: 'Company Documents',
    fileName: 'BGSPL_Appraisal_Matrix_2026.pdf',
    fileSize: '1.9 MB',
    fileType: 'PDF',
    uploadedBy: 'Kritika Gupta',
    uploadDate: '2026-04-01',
    description: 'KPI weighting metrics for exploration, consulting delivery, GIS projects, and client satisfaction.',
    accessRole: 'hr',
  },
  {
    id: 'cdoc-05',
    title: 'Employee Group Mediclaim & Term Life Insurance Policy',
    category: 'Company Documents',
    fileName: 'HDFC_ERGO_Corporate_Mediclaim_Guide.pdf',
    fileSize: '2.1 MB',
    fileType: 'PDF',
    uploadedBy: 'Kritika Gupta',
    uploadDate: '2026-01-10',
    description: 'Cashless hospital network in Jaipur/Bhilwara/Udaipur, maternity cover, and emergency claim procedures.',
    accessRole: 'all',
  },
  {
    id: 'cdoc-06',
    title: 'Aadhaar Card - Dr. Amit Kumar Bansal',
    category: 'Identity',
    fileName: 'Aadhaar_Amit_Bansal.pdf',
    fileSize: '1.2 MB',
    fileType: 'PDF',
    uploadedBy: 'Amit Kumar Bansal',
    uploadDate: '2022-10-02',
    description: 'UIDAI verified identity credential.',
    accessRole: 'hr',
  },
  {
    id: 'cdoc-07',
    title: 'PAN Card - Chhavi Bansal',
    category: 'Identity',
    fileName: 'PAN_Chhavi_Bansal.pdf',
    fileSize: '780 KB',
    fileType: 'PDF',
    uploadedBy: 'Chhavi Bansal',
    uploadDate: '2022-10-03',
    description: 'Income Tax Department permanent account card.',
    accessRole: 'hr',
  },
  {
    id: 'cdoc-08',
    title: 'First Class Mines Manager Certificate - Rajesh Sharma',
    category: 'Education',
    fileName: 'DGMS_FCCM_Certificate.pdf',
    fileSize: '1.8 MB',
    fileType: 'PDF',
    uploadedBy: 'Rajesh Sharma',
    uploadDate: '2022-11-12',
    description: 'Statutory certification from Directorate General of Mines Safety (DGMS).',
    accessRole: 'hr',
  },
];

export const INITIAL_EMPLOYEE_DOCUMENTS: EmployeeDocumentRecord[] = [
  {
    id: 'doc-rec-rohan-1',
    employeeId: 'BGS-006',
    employeeName: 'Rohan Deshmukh',
    department: 'Geology & Mineral Exploration',
    documentType: 'Degree / Diploma',
    fileName: 'M.Sc_Applied_Geology_Rajasthan_University.pdf',
    fileSize: '3.4 MB',
    uploadedOn: '2023-04-18',
    status: 'Verified',
  },
  {
    id: 'doc-rec-rohan-2',
    employeeId: 'BGS-006',
    employeeName: 'Rohan Deshmukh',
    department: 'Geology & Mineral Exploration',
    documentType: 'Aadhaar Card',
    fileName: 'Aadhaar_Card_Rohan_Deshmukh.pdf',
    fileSize: '1.2 MB',
    uploadedOn: '2023-04-18',
    status: 'Verified',
  },
  {
    id: 'doc-rec-rohan-3',
    employeeId: 'BGS-006',
    employeeName: 'Rohan Deshmukh',
    department: 'Geology & Mineral Exploration',
    documentType: 'DGMS Mining Competency',
    fileName: 'DGMS_Gas_Testing_Safety_Badge.pdf',
    fileSize: '2.1 MB',
    uploadedOn: '2023-07-22',
    status: 'Verified',
    expiryDate: '2028-07-21',
  },
  {
    id: 'doc-rec-1',
    employeeId: 'BGS-001',
    employeeName: 'Dr. Amit Kumar Bansal',
    department: 'Geology & Mineral Exploration',
    documentType: 'Degree / Diploma',
    fileName: 'Ph.D_Geology_IIT_Roorkee.pdf',
    fileSize: '4.2 MB',
    uploadedOn: '2022-04-10',
    status: 'Verified',
  },
  {
    id: 'doc-rec-2',
    employeeId: 'BGS-003',
    employeeName: 'Rajesh Sharma',
    department: 'Mining & Mine Planning',
    documentType: 'DGMS Mining Competency',
    fileName: 'DGMS_First_Class_Manager_Cert.pdf',
    fileSize: '2.8 MB',
    uploadedOn: '2023-01-15',
    status: 'Verified',
    expiryDate: '2028-01-14',
  },
  {
    id: 'doc-rec-3',
    employeeId: 'BGS-004',
    employeeName: 'Priya Meena',
    department: 'GIS & Remote Sensing',
    documentType: 'UAV Remote Pilot License',
    fileName: 'DGCA_Small_Category_Drone_Pilot.pdf',
    fileSize: '1.9 MB',
    uploadedOn: '2023-06-20',
    status: 'Verified',
    expiryDate: '2029-06-19',
  },
  {
    id: 'doc-rec-4',
    employeeId: 'BGS-005',
    employeeName: 'Vikram Singh Shekhawat',
    department: 'Mining Operations',
    documentType: 'DGMS Mining Competency',
    fileName: 'Overman_Competency_Certificate.pdf',
    fileSize: '3.1 MB',
    uploadedOn: '2023-11-05',
    status: 'Pending Review',
    expiryDate: '2027-11-04',
  },
  {
    id: 'doc-rec-5',
    employeeId: 'BGS-007',
    employeeName: 'Sunita Choudhary',
    department: 'Human Resources & Admin',
    documentType: 'PAN Card',
    fileName: 'PAN_Card_Sunita_Choudhary.pdf',
    fileSize: '1.1 MB',
    uploadedOn: '2024-02-01',
    status: 'Verified',
  },
  {
    id: 'doc-rec-6',
    employeeId: 'BGS-008',
    employeeName: 'Kavita Joshi',
    department: 'Finance & Accounts',
    documentType: 'Degree / Diploma',
    fileName: 'ICAI_Chartered_Accountant_Cert.pdf',
    fileSize: '2.4 MB',
    uploadedOn: '2023-08-12',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-1',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Rajesh Bansal',
    department: 'Executive Board',
    documentType: 'Degree / Diploma',
    fileName: 'Ph.D_Mining_Geology_ISM_Dhanbad.pdf',
    fileSize: '4.8 MB',
    uploadedOn: '2021-04-01',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-2',
    employeeId: 'BGS-2021-001',
    employeeName: 'Dr. Rajesh Bansal',
    department: 'Executive Board',
    documentType: 'Aadhaar Card',
    fileName: 'Aadhaar_Card_Rajesh_Bansal.pdf',
    fileSize: '1.3 MB',
    uploadedOn: '2021-04-01',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-3',
    employeeId: 'BGS-2021-009',
    employeeName: 'Pooja Joshi',
    department: 'Human Resources',
    documentType: 'Degree / Diploma',
    fileName: 'MBA_HR_Management_Symbiosis.pdf',
    fileSize: '2.9 MB',
    uploadedOn: '2021-07-15',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-4',
    employeeId: 'BGS-2021-009',
    employeeName: 'Pooja Joshi',
    department: 'Human Resources',
    documentType: 'PAN Card',
    fileName: 'PAN_Card_Pooja_Joshi.pdf',
    fileSize: '1.0 MB',
    uploadedOn: '2021-07-15',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-5',
    employeeId: 'BGS-2022-011',
    employeeName: 'Ramesh Iyer',
    department: 'Finance & Accounts',
    documentType: 'Degree / Diploma',
    fileName: 'ICAI_FCA_Chartered_Accountant.pdf',
    fileSize: '3.6 MB',
    uploadedOn: '2022-01-10',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-6',
    employeeId: 'BGS-2022-011',
    employeeName: 'Ramesh Iyer',
    department: 'Finance & Accounts',
    documentType: 'PAN Card',
    fileName: 'PAN_Card_Ramesh_Iyer.pdf',
    fileSize: '1.1 MB',
    uploadedOn: '2022-01-10',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-7',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Geology & Mineral Exploration',
    documentType: 'DGMS Mining Competency',
    fileName: 'DGMS_Geological_Surveyor_Certificate.pdf',
    fileSize: '2.6 MB',
    uploadedOn: '2022-06-01',
    status: 'Verified',
    expiryDate: '2028-05-31',
  },
  {
    id: 'doc-rec-mb-8',
    employeeId: 'BGS-2022-018',
    employeeName: 'Vikram Patel',
    department: 'Geology & Mineral Exploration',
    documentType: 'Aadhaar Card',
    fileName: 'Aadhaar_Card_Vikram_Patel.pdf',
    fileSize: '1.4 MB',
    uploadedOn: '2022-06-01',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-9',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    documentType: 'Aadhaar Card',
    fileName: 'Aadhaar_Card_Neha_Gupta.pdf',
    fileSize: '1.2 MB',
    uploadedOn: '2023-08-15',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-10',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    documentType: 'PAN Card',
    fileName: 'PAN_Card_Neha_Gupta.pdf',
    fileSize: '950 KB',
    uploadedOn: '2023-08-15',
    status: 'Verified',
  },
  {
    id: 'doc-rec-mb-11',
    employeeId: 'BGS-2023-044',
    employeeName: 'Neha Gupta',
    department: 'Geology & Mineral Exploration',
    documentType: 'UAV Remote Pilot License',
    fileName: 'DGCA_Small_Category_Drone_Pilot_Neha.pdf',
    fileSize: '2.1 MB',
    uploadedOn: '2024-03-10',
    status: 'Pending Review',
    expiryDate: '2029-03-09',
  },
];
