import { StyleSheet } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
  },
  editBtnText: {
    ...typography.bodySmall,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  heroBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    backgroundColor: colors.background.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
    gap: spacing.md,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primaryLight,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    ...typography.h3,
    fontWeight: '800',
    color: colors.primary,
  },
  heroInfo: {
    flex: 1,
  },
  heroNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroName: {
    ...typography.h4,
    fontWeight: '800',
    color: colors.text.primary,
    flexShrink: 1,
  },
  kycVerifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#E6F4EA',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
  },
  kycVerifiedText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.success,
  },
  heroDesig: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: '700',
  },
  heroDept: {
    ...typography.caption,
    color: colors.text.secondary,
    marginBottom: 4,
  },
  heroBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  empIdPill: {
    backgroundColor: colors.background.tertiary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  empIdPillText: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '700',
    color: colors.text.secondary,
  },
  roleText: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  heroContactStrip: {
    gap: spacing.sm,
  },
  contactCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.border.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabsContainer: {
    backgroundColor: colors.background.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  tabsScroll: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  tabChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: borderRadius.full,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  tabChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  tabChipText: {
    ...typography.caption,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  tabChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  content: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  tabSection: {
    gap: spacing.md,
  },
  kpiRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  kpiCard: {
    flex: 1,
    padding: spacing.md,
    alignItems: 'center',
    borderRadius: borderRadius.md,
    gap: 2,
  },
  kpiValue: {
    ...typography.h4,
    fontWeight: '800',
    color: colors.primary,
    marginTop: 4,
  },
  kpiLabel: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
  },
  card: {
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
  },
  sectionHeading: {
    ...typography.bodyLarge,
    fontWeight: '800',
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  cardTitleWithBadge: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  dataGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: spacing.md,
  },
  dataItem: {
    width: '50%',
    paddingRight: spacing.sm,
  },
  dataLabel: {
    ...typography.caption,
    fontSize: 10,
    fontWeight: '700',
    color: colors.text.tertiary,
    textTransform: 'uppercase',
  },
  dataValue: {
    ...typography.bodySmall,
    color: colors.text.primary,
    fontWeight: '600',
    marginTop: 2,
  },
  monoValue: {
    fontFamily: 'monospace',
    color: colors.primary,
  },
  emergencyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  emergencyBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  emergencyName: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  emergencyRel: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  emergencyCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.danger,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
  },
  emergencyCallBtnText: {
    ...typography.bodySmall,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  logRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  logDateBlock: {
    gap: 2,
  },
  logDate: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  logLocation: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
  },
  logTimes: {
    alignItems: 'center',
  },
  logTimeText: {
    ...typography.caption,
    fontSize: 11,
    color: colors.text.secondary,
  },
  balanceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  balanceItem: {
    width: '48%',
    backgroundColor: colors.background.secondary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  balanceType: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  balanceAvailable: {
    ...typography.h3,
    fontWeight: '800',
    color: colors.success,
  },
  balanceSub: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.tertiary,
  },
  leaveReqRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  leaveReqType: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  leaveReqDates: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  leaveReqReason: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
    fontStyle: 'italic',
  },
  salaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  salaryLabel: {
    ...typography.bodySmall,
    color: colors.text.secondary,
  },
  salaryVal: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  totalSalaryRow: {
    backgroundColor: colors.background.secondary,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.sm,
    marginTop: spacing.xs,
  },
  totalSalaryLabel: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  totalSalaryVal: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: colors.primary,
  },
  netSalaryRow: {
    backgroundColor: '#E8F5E9',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    marginTop: spacing.sm,
  },
  netSalaryLabel: {
    ...typography.body,
    fontWeight: '800',
    color: colors.success,
  },
  netSalaryVal: {
    ...typography.h4,
    fontWeight: '800',
    color: colors.success,
  },
  payslipRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  payslipMonth: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  payslipNet: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  claimRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  claimCategory: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  claimDesc: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  claimDate: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
  },
  claimAmount: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: colors.primary,
  },
  apprHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
    paddingBottom: spacing.sm,
    marginBottom: spacing.sm,
  },
  apprCycle: {
    ...typography.bodyLarge,
    fontWeight: '800',
    color: colors.text.primary,
  },
  apprReviewer: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  scoreBadge: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
    borderRadius: borderRadius.md,
  },
  scoreText: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: colors.primary,
  },
  ratingsList: {
    gap: 4,
    marginBottom: spacing.md,
  },
  ratingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  ratingName: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  ratingScore: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  feedbackBlock: {
    backgroundColor: colors.background.secondary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  feedbackLabel: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.tertiary,
    textTransform: 'uppercase',
  },
  feedbackText: {
    ...typography.bodySmall,
    color: colors.text.primary,
    fontStyle: 'italic',
    marginTop: 2,
  },
  exitHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  clearanceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  clearanceDept: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  clearanceReviewer: {
    ...typography.caption,
    color: colors.text.secondary,
    fontSize: 10,
  },
  clearanceNotes: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
  },
  fnfBox: {
    backgroundColor: colors.background.secondary,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginTop: spacing.md,
  },
  fnfTitle: {
    ...typography.body,
    fontWeight: '800',
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  emptyNote: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontStyle: 'italic',
    paddingVertical: spacing.sm,
  },
  helperNotice: {
    ...typography.caption,
    fontSize: 11,
    color: colors.text.tertiary,
    marginTop: spacing.sm,
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xxl,
  },
  errorTitle: {
    ...typography.h3,
    fontWeight: '800',
    color: colors.text.primary,
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  errorMessage: {
    ...typography.body,
    color: colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  manageDocsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#EFF6FF',
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.sm,
  },
  manageDocsBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  emptyDocsBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.xs,
  },
  emptyDocsText: {
    ...typography.caption,
    color: colors.text.tertiary,
    textAlign: 'center',
    maxWidth: 240,
  },
  uploadDocPromptBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
    marginTop: spacing.xs,
  },
  uploadDocPromptBtnText: {
    ...typography.bodySmall,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  docCardsList: {
    gap: spacing.sm,
  },
  docRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
    gap: spacing.sm,
  },
  docRowIconWrap: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docRowInfo: {
    flex: 1,
  },
  docRowType: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  docRowMeta: {
    ...typography.caption,
    fontFamily: 'monospace',
    color: colors.text.tertiary,
    fontSize: 10,
    marginTop: 1,
  },
  docRowDate: {
    ...typography.caption,
    color: colors.text.secondary,
    fontSize: 10,
    marginTop: 2,
  },
  docRowRight: {
    alignItems: 'flex-end',
    gap: 6,
  },
  docRowInspectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#EFF6FF',
  },
  docRowInspectText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.primary,
  },
});
