import { StyleSheet } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  headerIconBtn: {
    padding: spacing.xs,
    backgroundColor: `${colors.primary}15`,
    borderRadius: borderRadius.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBar: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
    backgroundColor: colors.background.secondary,
  },
  tabsScroll: {
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  tabItem: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    position: 'relative',
  },
  tabItemActive: {
    borderBottomColor: colors.primary,
  },
  tabLabel: {
    ...typography.bodySmall,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  badgeDot: {
    position: 'absolute',
    top: 8,
    right: 2,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.semantic.danger,
  },
  content: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
  },
  heroCard: {
    padding: spacing.md,
    backgroundColor: `${colors.primary}08`,
    borderColor: `${colors.primary}25`,
  },
  heroRow: {
    flexDirection: 'row',
    gap: spacing.md,
    alignItems: 'center',
  },
  heroBadge: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.md,
    backgroundColor: `${colors.primary}20`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroTitle: {
    ...typography.h4,
    color: colors.text.primary,
  },
  heroSub: {
    ...typography.caption,
    color: colors.text.secondary,
    marginTop: 2,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: 4,
  },
  heroMetaText: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
  },
  heroActionBtn: {
    marginTop: spacing.sm,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: `${colors.primary}15`,
  },
  heroActionText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.primary,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  kpiCard: {
    flex: 1,
    minWidth: '47%',
    padding: spacing.sm,
    alignItems: 'flex-start',
  },
  kpiIconWrap: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  kpiValue: {
    ...typography.h3,
    color: colors.text.primary,
  },
  kpiLabel: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  sectionTitle: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  sectionSub: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  subSectionTitle: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.secondary,
    marginTop: spacing.xs,
  },
  linkText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.primary,
  },
  emptyNoteCard: {
    padding: spacing.lg,
    alignItems: 'center',
    gap: spacing.xs,
  },
  emptyNoteTitle: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  emptyNoteSub: {
    ...typography.caption,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  orderActionCard: {
    padding: spacing.md,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  woCode: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.text.tertiary,
  },
  woTitle: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  woScope: {
    ...typography.caption,
    color: colors.text.secondary,
    marginTop: 2,
  },
  woDivider: {
    height: 1,
    backgroundColor: colors.border.subtle,
    marginVertical: spacing.sm,
  },
  actionBtnRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  tenderCard: {
    padding: spacing.md,
  },
  timeTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: `${colors.semantic.warning}15`,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: borderRadius.sm,
  },
  timeTagText: {
    ...typography.caption,
    fontSize: 10,
    fontWeight: '700',
    color: colors.semantic.warning,
  },
  metaPillsRow: {
    flexDirection: 'row',
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.sm,
    padding: spacing.xs,
    marginTop: spacing.sm,
  },
  metaPill: {
    flex: 1,
    alignItems: 'center',
  },
  metaPillLabel: {
    ...typography.caption,
    fontSize: 9,
    color: colors.text.tertiary,
  },
  metaPillVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    height: 40,
    ...typography.bodySmall,
    color: colors.text.primary,
  },
  filterScroll: {
    gap: spacing.xs,
  },
  catFilterChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  catFilterChipActive: {
    backgroundColor: `${colors.primary}15`,
    borderColor: colors.primary,
  },
  catFilterText: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  catFilterTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  saveBtn: {
    padding: 4,
  },
  tenderOrg: {
    ...typography.caption,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  tenderStatsRow: {
    flexDirection: 'row',
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    marginVertical: spacing.xs,
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
  },
  statBoxLabel: {
    ...typography.caption,
    fontSize: 9,
    color: colors.text.tertiary,
  },
  statBoxVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  myBidVaultBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: `${colors.semantic.success}10`,
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    marginTop: spacing.sm,
  },
  myBidVaultTitle: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.semantic.success,
  },
  myBidVaultSub: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.secondary,
  },
  cardActionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  bidCard: {
    padding: spacing.md,
  },
  bidFinancialsBox: {
    flexDirection: 'row',
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    marginTop: spacing.xs,
  },
  bidBoxLabel: {
    ...typography.caption,
    fontSize: 9,
    color: colors.text.tertiary,
  },
  bidBoxVal: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  bidRemarksText: {
    ...typography.caption,
    color: colors.text.secondary,
    marginTop: spacing.xs,
  },
  bidActionsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
    alignItems: 'center',
  },
  withdrawBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: `${colors.semantic.danger}40`,
    borderRadius: borderRadius.sm,
  },
  withdrawBtnText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.semantic.danger,
  },
  clarificationCard: {
    padding: spacing.md,
  },
  clarificationTenderId: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  clarificationDate: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
  },
  clarificationQuestion: {
    ...typography.bodySmall,
    fontWeight: '600',
    color: colors.text.primary,
    marginVertical: spacing.xs,
  },
  clarificationAnswerBox: {
    backgroundColor: `${colors.semantic.success}10`,
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.semantic.success,
  },
  answerHeader: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.semantic.success,
  },
  answerBody: {
    ...typography.caption,
    color: colors.text.primary,
    marginTop: 2,
  },
  pendingAnswerBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  pendingAnswerText: {
    ...typography.caption,
    color: colors.semantic.warning,
    fontSize: 10,
  },
  orderCard: {
    padding: spacing.md,
  },
  progressWrap: {
    marginTop: spacing.sm,
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.background.tertiary,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.primary,
  },
  progressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  progressSub: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.secondary,
  },
  progressPct: {
    ...typography.caption,
    fontSize: 10,
    fontWeight: '700',
    color: colors.primary,
  },
  stageNoteBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: `${colors.primary}08`,
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    marginTop: spacing.sm,
  },
  stageNoteText: {
    ...typography.caption,
    color: colors.primary,
    flex: 1,
  },
  orderActionsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  summaryBox: {
    flex: 1,
    padding: spacing.md,
  },
  summaryBoxLabel: {
    ...typography.caption,
    fontSize: 9,
    color: colors.text.tertiary,
    fontWeight: '700',
  },
  summaryBoxVal: {
    ...typography.h3,
    color: colors.text.primary,
    marginTop: 2,
  },
  paymentCard: {
    padding: spacing.md,
  },
  paymentBreakdown: {
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.sm,
    padding: spacing.sm,
    marginTop: spacing.xs,
    gap: 4,
  },
  payRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  payLabel: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  payVal: {
    ...typography.caption,
    fontWeight: '600',
    color: colors.text.primary,
  },
  netPayRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    paddingTop: 4,
    marginTop: 2,
  },
  netPayLabel: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  netPayVal: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: colors.semantic.success,
  },
  utrTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: spacing.sm,
  },
  utrText: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '600',
    fontSize: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background.primary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  modalTitle: {
    ...typography.h3,
    color: colors.text.primary,
  },
  modalSub: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  modalCloseBtn: {
    padding: spacing.xs,
  },
  profileSection: {
    backgroundColor: colors.background.secondary,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    gap: spacing.xs,
  },
  profileSectionTitle: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.text.tertiary,
    fontSize: 10,
    marginBottom: 4,
  },
  profileRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  profileLabel: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  profileVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  inputLabel: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.secondary,
  },
  textInput: {
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    ...typography.bodySmall,
    color: colors.text.primary,
  },
  ceilingHint: {
    ...typography.caption,
    color: colors.semantic.info,
    fontSize: 10,
  },
  fileChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.xs,
    backgroundColor: `${colors.primary}10`,
    borderRadius: borderRadius.sm,
  },
  fileNameText: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '600',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
});
