import { StyleSheet } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  approvalsHeaderBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
  },
  approvalsHeaderText: {
    ...typography.caption,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  pendingBadge: {
    backgroundColor: colors.semantic.danger,
    borderRadius: 999,
    paddingHorizontal: 5,
    paddingVertical: 1,
    minWidth: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colors.background.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
    gap: spacing.sm,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: borderRadius.md,
    backgroundColor: colors.background.tertiary,
  },
  tabButtonActive: {
    backgroundColor: `${colors.primary}18`,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  tabButtonText: {
    ...typography.caption,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  tabButtonTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  scrollContent: {
    padding: spacing.md,
    paddingBottom: 40,
    gap: spacing.sm,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  sectionTitle: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.text.tertiary,
    letterSpacing: 0.8,
  },
  sectionSubtitle: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontWeight: '600',
  },
  recordsCount: {
    ...typography.caption,
    color: colors.text.tertiary,
  },
  balanceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    justifyContent: 'space-between',
  },
  balanceCard: {
    width: '48.5%',
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs,
  },
  balCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  balTitle: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.secondary,
    flex: 1,
    fontSize: 11,
  },
  colorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 4,
  },
  balNumbersRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    marginVertical: 2,
  },
  balAvailableNum: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text.primary,
  },
  balTotalNum: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontWeight: '600',
  },
  progressBarBg: {
    height: 4,
    backgroundColor: colors.background.tertiary,
    borderRadius: 2,
    marginVertical: 6,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 2,
  },
  balCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  balFooterText: {
    fontSize: 10,
    color: colors.text.tertiary,
  },
  balPendingText: {
    fontSize: 10,
    color: colors.semantic.warning,
    fontWeight: '600',
  },
  applyBtn: {
    marginVertical: spacing.xs,
  },
  filterSection: {
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    height: 38,
    gap: spacing.xs,
  },
  searchInput: {
    flex: 1,
    ...typography.bodySmall,
    color: colors.text.primary,
    paddingVertical: 0,
  },
  statusChipsRow: {
    gap: spacing.xs,
    paddingVertical: 2,
  },
  statusChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  statusChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  statusChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  statusChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  card: {
    padding: spacing.md,
    marginBottom: spacing.xs,
    borderRadius: borderRadius.md,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    flexWrap: 'wrap',
  },
  typePill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: borderRadius.sm,
  },
  typePillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  applicantBadge: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  dateSpan: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  daysBadge: {
    backgroundColor: colors.background.tertiary,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: borderRadius.sm,
    marginLeft: 'auto',
  },
  daysBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  partialBanner: {
    backgroundColor: `${colors.semantic.warning}15`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: borderRadius.sm,
    marginBottom: 4,
  },
  partialText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.semantic.warning,
  },
  reasonText: {
    ...typography.caption,
    color: colors.text.secondary,
    lineHeight: 16,
    marginBottom: 6,
  },
  rejectionBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: `${colors.semantic.danger}12`,
    padding: 6,
    borderRadius: borderRadius.sm,
    marginBottom: 6,
  },
  rejectionText: {
    ...typography.caption,
    color: colors.semantic.danger,
    fontWeight: '600',
    flex: 1,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    paddingTop: 6,
    marginTop: 2,
  },
  submittedOnText: {
    fontSize: 10,
    color: colors.text.tertiary,
  },
  viewDetailLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  viewDetailText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'flex-end',
  },
  applyModalBox: {
    backgroundColor: colors.background.secondary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: '90%',
    paddingBottom: 24,
  },
  detailModalBox: {
    backgroundColor: colors.background.secondary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: '85%',
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  modalTitle: {
    ...typography.h3,
    color: colors.text.primary,
  },
  modalSubtitle: {
    ...typography.caption,
    color: colors.text.tertiary,
    marginTop: 2,
  },
  closeBtn: {
    padding: 4,
  },
  applyFormScroll: {
    padding: spacing.md,
    gap: spacing.sm,
  },
  detailScroll: {
    padding: spacing.md,
    gap: spacing.md,
  },
  applicantInfoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  applicantInfoText: {
    ...typography.bodySmall,
    color: colors.text.secondary,
  },
  inputLabel: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.secondary,
    marginBottom: 4,
  },
  typeSelectorWrap: {
    gap: 6,
  },
  typeSelectCard: {
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
  },
  typeSelectCardActive: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}10`,
  },
  typeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  typeSelectTitle: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  typeSelectTitleActive: {
    color: colors.primary,
  },
  typeAvailBadge: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  typeAvailBadgeActive: {
    color: colors.primary,
  },
  typeCodeSub: {
    fontSize: 10,
    color: colors.text.tertiary,
    marginTop: 2,
  },
  dateInputsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  engineBanner: {
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    gap: 6,
  },
  engineBannerSuccess: {
    backgroundColor: `${colors.semantic.success}10`,
    borderColor: `${colors.semantic.success}40`,
  },
  engineBannerError: {
    backgroundColor: `${colors.semantic.danger}10`,
    borderColor: `${colors.semantic.danger}40`,
  },
  engineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  engineTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  engineTitle: {
    ...typography.bodySmall,
    fontWeight: '800',
  },
  projectedBalText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.secondary,
  },
  skippedWrap: {
    marginTop: 4,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  skippedTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.text.tertiary,
    marginBottom: 4,
  },
  skippedChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  skippedChip: {
    backgroundColor: colors.background.secondary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  skippedChipText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  errorAlertText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.semantic.danger,
    marginTop: 2,
  },
  warningAlertText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.semantic.warning,
    marginTop: 2,
  },
  overlapBox: {
    gap: 6,
    marginTop: 4,
  },
  autoAdjustBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: borderRadius.sm,
    alignSelf: 'flex-start',
  },
  autoAdjustBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  charCountText: {
    fontSize: 10,
    color: colors.text.tertiary,
    textAlign: 'right',
    marginTop: -4,
  },
  formActionButtons: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  detailHero: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  detailHeroType: {
    ...typography.h3,
    color: colors.text.primary,
  },
  detailHeroDept: {
    ...typography.caption,
    color: colors.text.secondary,
    marginTop: 2,
  },
  detailMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  detailMetaItem: {
    width: '47%',
  },
  detailMetaLabel: {
    fontSize: 10,
    color: colors.text.tertiary,
    fontWeight: '600',
  },
  detailMetaVal: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
    marginTop: 2,
  },
  partialCard: {
    flexDirection: 'row',
    backgroundColor: `${colors.semantic.warning}15`,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
  },
  partialCardCol: {
    flex: 1,
    alignItems: 'center',
  },
  partialCardDivider: {
    width: 1,
    backgroundColor: `${colors.semantic.warning}40`,
  },
  partialCardLabel: {
    fontSize: 10,
    color: colors.text.tertiary,
    fontWeight: '600',
  },
  partialCardValGreen: {
    ...typography.body,
    fontWeight: '800',
    color: colors.semantic.success,
    marginTop: 2,
  },
  partialCardValRed: {
    ...typography.body,
    fontWeight: '800',
    color: colors.semantic.danger,
    marginTop: 2,
  },
  sectionBlock: {
    gap: 4,
  },
  sectionBlockTitle: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  reasonCard: {
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  reasonCardText: {
    ...typography.bodySmall,
    color: colors.text.primary,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  contactText: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  rejectionDetailBox: {
    backgroundColor: `${colors.semantic.danger}12`,
    borderWidth: 1,
    borderColor: `${colors.semantic.danger}30`,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    gap: 6,
  },
  rejectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rejectionHeaderTitle: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: colors.semantic.danger,
  },
  rejectionDetailBody: {
    ...typography.bodySmall,
    color: colors.text.primary,
    lineHeight: 18,
  },
  adjudicatorSign: {
    fontSize: 10,
    color: colors.text.tertiary,
    fontStyle: 'italic',
    marginTop: 2,
  },
  approvalDetailBox: {
    backgroundColor: `${colors.semantic.success}12`,
    borderWidth: 1,
    borderColor: `${colors.semantic.success}30`,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    gap: 6,
  },
  approvalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  approvalHeaderTitle: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: colors.semantic.success,
  },
  approvalDetailBody: {
    ...typography.bodySmall,
    color: colors.text.primary,
    lineHeight: 18,
  },
  cancelActionWrap: {
    marginTop: spacing.xs,
  },
  hrAdjudicateWrap: {
    marginTop: spacing.xs,
  },
});
