import { StyleSheet } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  headerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: borderRadius.sm,
    backgroundColor: `${colors.primary}15`,
  },
  headerBtnText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.primary,
  },
  tabsWrap: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.background.primary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  content: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl * 2,
  },
  tabContent: {
    gap: spacing.md,
  },
  kpiGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  kpiCol: {
    flex: 1,
  },
  sectionHeader: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.text.tertiary,
    letterSpacing: 0.5,
    marginTop: spacing.xs,
  },
  actionGrid: {
    gap: spacing.sm,
  },
  actionTile: {
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
  },
  tileIconBox: {
    width: 38,
    height: 38,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  tileTitle: {
    ...typography.h4,
    color: colors.text.primary,
    marginBottom: 2,
  },
  tileSub: {
    ...typography.caption,
    color: colors.text.secondary,
    lineHeight: 16,
  },
  tileFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.sm,
  },
  tileLink: {
    ...typography.caption,
    fontWeight: '700',
  },
  recentSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  seeAllText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.primary,
  },
  runCard: {
    padding: spacing.md,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  runHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  runMonth: {
    ...typography.h4,
    color: colors.text.primary,
  },
  runDate: {
    ...typography.caption,
    color: colors.text.tertiary,
    marginTop: 1,
  },
  runMetaGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    marginBottom: spacing.sm,
  },
  runMetaItem: {
    alignItems: 'center',
  },
  runMetaLabel: {
    ...typography.caption,
    fontSize: 8,
    fontWeight: '700',
    color: colors.text.tertiary,
    marginBottom: 2,
  },
  runMetaVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  runFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    paddingTop: spacing.xs,
  },
  runAuthor: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.secondary,
  },
  runViewSlipsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  runViewSlipsText: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.primary,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  searchInput: {
    flex: 1,
    ...typography.bodySmall,
    color: colors.text.primary,
    padding: 0,
  },
  filterScroll: {
    gap: spacing.xs,
    paddingVertical: 2,
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: {
    ...typography.caption,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#FFFFFF',
  },
  resultCountText: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 11,
  },
  structureCard: {
    padding: spacing.md,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  structHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  structTitleWrap: {
    flex: 1,
  },
  structEmpId: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.primary,
  },
  structEmpName: {
    ...typography.h4,
    color: colors.text.primary,
    marginTop: 1,
  },
  structEmpRole: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  structCtcBadge: {
    backgroundColor: `${colors.primary}12`,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.sm,
    alignItems: 'flex-end',
  },
  structCtcLabel: {
    ...typography.caption,
    fontSize: 8,
    fontWeight: '700',
    color: colors.primary,
  },
  structCtcVal: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.primary,
  },
  compGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    marginBottom: spacing.sm,
  },
  compCol: {
    alignItems: 'center',
  },
  compLabel: {
    ...typography.caption,
    fontSize: 8,
    fontWeight: '700',
    color: colors.text.tertiary,
    marginBottom: 2,
  },
  compVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  structFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    paddingTop: spacing.xs,
  },
  grossMonthlyLabel: {
    ...typography.caption,
    fontSize: 9,
    color: colors.text.tertiary,
  },
  grossMonthlyVal: {
    ...typography.bodySmall,
    fontWeight: '700',
    color: colors.text.primary,
  },
  netHighlight: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.sm,
  },
  netHighlightLabel: {
    ...typography.caption,
    fontSize: 8,
    fontWeight: '700',
    color: '#059669',
  },
  netHighlightVal: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: '#059669',
  },
  stepCard: {
    padding: spacing.md,
    backgroundColor: colors.background.secondary,
  },
  stepTitle: {
    ...typography.h4,
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  cycleChips: {
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  cycleChip: {
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  cycleChipActive: {
    backgroundColor: `${colors.primary}15`,
    borderColor: colors.primary,
  },
  cycleChipText: {
    ...typography.bodySmall,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  cycleChipTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  syncStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  syncStatusText: {
    ...typography.caption,
    fontSize: 10,
    color: '#059669',
    fontWeight: '600',
  },
  rosterCard: {
    padding: spacing.md,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  rosterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  rosterEmpId: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.primary,
  },
  rosterEmpName: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  rosterEmpDept: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  rosterDaysBadge: {
    alignItems: 'flex-end',
  },
  rosterDaysLabel: {
    ...typography.caption,
    fontSize: 8,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  rosterDaysVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  rosterLopText: {
    ...typography.caption,
    fontSize: 10,
    color: colors.semantic.danger,
    fontWeight: '700',
  },
  rosterFinancials: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  rosterFinCol: {
    alignItems: 'center',
  },
  rosterFinLabel: {
    ...typography.caption,
    fontSize: 8,
    color: colors.text.tertiary,
    marginBottom: 2,
  },
  rosterFinVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  successCard: {
    padding: spacing.xl,
    alignItems: 'center',
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  successIconBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#ECFDF5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  successTitle: {
    ...typography.h3,
    color: colors.text.primary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  successDesc: {
    ...typography.bodySmall,
    color: colors.text.secondary,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: spacing.lg,
  },
  successSummaryBox: {
    width: '100%',
    backgroundColor: colors.background.tertiary,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    gap: 4,
    marginBottom: spacing.lg,
  },
  successSummaryText: {
    ...typography.caption,
    color: colors.text.primary,
    fontWeight: '600',
  },
  successActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    width: '100%',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background.secondary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: '90%',
    padding: spacing.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
    paddingBottom: spacing.sm,
    marginBottom: spacing.md,
  },
  modalTitle: {
    ...typography.h4,
    color: colors.text.primary,
  },
  modalSubtitle: {
    ...typography.caption,
    color: colors.text.secondary,
    marginTop: 1,
  },
  closeBtn: {
    padding: spacing.xs,
  },
  modalScroll: {
    paddingBottom: spacing.lg,
    gap: spacing.sm,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: `${colors.semantic.danger}15`,
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
  },
  errorText: {
    ...typography.caption,
    color: colors.semantic.danger,
    fontWeight: '600',
  },
  modalSectionTitle: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.text.primary,
    letterSpacing: 0.5,
  },
  inputGroup: {
    gap: 4,
  },
  inputLabel: {
    ...typography.caption,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  numInput: {
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    color: colors.text.primary,
    ...typography.body,
    fontWeight: '600',
  },
  computedBox: {
    backgroundColor: colors.background.tertiary,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
    marginTop: spacing.md,
    gap: 6,
  },
  computedTitle: {
    ...typography.caption,
    fontSize: 9,
    fontWeight: '800',
    color: colors.text.tertiary,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  computedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  computedRowNet: {
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    paddingTop: 6,
    marginTop: 4,
  },
  computedLabel: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  computedVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.primary,
  },
  computedNetLabel: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: '#059669',
  },
  computedNetVal: {
    ...typography.bodySmall,
    fontWeight: '800',
    color: '#059669',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
});
