import { StyleSheet, Platform } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  contentContainer: {
    padding: spacing.md,
    gap: spacing.md,
  },
  headerActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: borderRadius.md,
    gap: 4,
  },
  headerActionText: {
    ...typography.caption,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  kpiContainer: {
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    backgroundColor: colors.background.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: colors.surfaceCard,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  kpiActionCard: {
    backgroundColor: `${colors.primary}10`,
    borderColor: `${colors.primary}30`,
    justifyContent: 'center',
  },
  kpiValue: {
    ...typography.h4,
    color: colors.text.primary,
    fontWeight: '800',
  },
  kpiLabel: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.tertiary,
    marginTop: 2,
    textAlign: 'center',
  },
  kpiActionLabel: {
    ...typography.caption,
    fontSize: 10,
    color: colors.primary,
    fontWeight: '700',
    marginTop: 4,
    textAlign: 'center',
  },
  tabBar: {
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    backgroundColor: colors.background.secondary,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.surfaceCard,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  tabButtonActive: {
    backgroundColor: `${colors.primary}15`,
    borderColor: colors.primary,
  },
  tabButtonText: {
    ...typography.caption,
    fontWeight: '600',
    color: colors.text.tertiary,
  },
  tabButtonTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  searchRow: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  searchInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceCard,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.light,
    paddingHorizontal: spacing.sm,
    height: 40,
    gap: spacing.xs,
  },
  searchInput: {
    flex: 1,
    ...typography.body,
    color: colors.text.primary,
    paddingVertical: 0,
  },
  filterScroll: {
    paddingHorizontal: spacing.md,
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  filterChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surfaceCard,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: {
    ...typography.caption,
    fontSize: 11,
    color: colors.text.secondary,
  },
  filterChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  listContainer: {
    padding: spacing.md,
    gap: spacing.md,
  },
  shiftCard: {
    padding: spacing.md,
  },
  shiftCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  shiftCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  shiftCardCode: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.primary,
    fontSize: 11,
  },
  shiftCardName: {
    ...typography.h4,
    fontSize: 15,
    color: colors.text.primary,
  },
  shiftTimingBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    marginBottom: spacing.sm,
  },
  shiftTimeCol: {
    flex: 1,
  },
  shiftTimeLabel: {
    ...typography.caption,
    fontSize: 9,
    fontWeight: '700',
    color: colors.text.tertiary,
  },
  shiftTimeVal: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  shiftHoursBadge: {
    backgroundColor: `${colors.primary}15`,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    borderRadius: borderRadius.sm,
  },
  shiftHoursText: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  metaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.surfaceCard,
    borderWidth: 1,
    borderColor: colors.border.light,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: borderRadius.sm,
  },
  metaBadgeText: {
    ...typography.caption,
    fontSize: 11,
    color: colors.text.secondary,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    paddingTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  locationWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  locationText: {
    ...typography.caption,
    fontSize: 11,
    color: colors.text.tertiary,
  },
  staffCountWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  staffCountText: {
    ...typography.caption,
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    paddingTop: spacing.sm,
  },
  actionBtnSecondary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border.light,
    backgroundColor: colors.background.secondary,
  },
  actionBtnTextSecondary: {
    ...typography.caption,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  actionBtnDanger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: `${colors.danger}30`,
    backgroundColor: `${colors.danger}10`,
  },
  actionBtnTextDanger: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.danger,
  },
  assignmentCard: {
    padding: spacing.md,
  },
  asgnHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  asgnEmpWrap: {
    flex: 1,
  },
  asgnEmpId: {
    ...typography.caption,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: '700',
    color: colors.primary,
  },
  asgnEmpName: {
    ...typography.h4,
    fontSize: 15,
    color: colors.text.primary,
    marginTop: 2,
  },
  asgnDept: {
    ...typography.caption,
    color: colors.text.tertiary,
    marginTop: 1,
  },
  asgnBody: {
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    paddingTop: spacing.sm,
    gap: spacing.xs,
  },
  asgnItem: {
    marginBottom: 4,
  },
  asgnItemLabel: {
    ...typography.caption,
    fontSize: 9,
    color: colors.text.tertiary,
    fontWeight: '700',
  },
  asgnItemValue: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  asgnGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.background.tertiary,
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
  },
  asgnSubItem: {
    flex: 1,
  },
  asgnSubVal: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.secondary,
    marginTop: 1,
  },

  heroCard: {
    padding: spacing.lg,
    backgroundColor: colors.surfaceCard,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  heroBadgeText: {
    ...typography.caption,
    fontSize: 10,
    fontWeight: '800',
    color: colors.primary,
  },
  heroShiftTitle: {
    ...typography.h3,
    color: colors.text.primary,
    marginTop: spacing.xs,
  },
  heroShiftCode: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.tertiary,
    marginBottom: spacing.md,
  },
  heroTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.tertiary,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginBottom: spacing.md,
  },
  heroTimeBox: {
    alignItems: 'center',
  },
  heroTimeLabel: {
    ...typography.caption,
    fontSize: 9,
    fontWeight: '700',
    color: colors.text.tertiary,
    marginBottom: 2,
  },
  heroTimeValue: {
    ...typography.bodyLarge,
    fontWeight: '800',
    color: colors.text.primary,
  },
  heroDetailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  heroDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '48%',
  },
  heroDetailText: {
    ...typography.caption,
    color: colors.text.secondary,
  },
  heroDesc: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontStyle: 'italic',
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    paddingTop: spacing.xs,
    marginTop: spacing.xs,
  },
  monthlyRosterBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  bannerIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerTitle: {
    ...typography.bodyLarge,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  bannerSubtitle: {
    ...typography.caption,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 1,
  },
  sectionHeader: {
    marginTop: spacing.sm,
  },
  sectionTitle: {
    ...typography.h4,
    color: colors.text.primary,
  },
  weeklyTableCard: {
    padding: 0,
    overflow: 'hidden',
  },
  rosterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  rosterRowActive: {
    backgroundColor: `${colors.primary}10`,
  },
  rosterDayCol: {
    width: 60,
  },
  rosterDayText: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  rosterDateText: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
  },
  rosterShiftCol: {
    flex: 1,
    paddingHorizontal: spacing.sm,
  },
  rosterShiftName: {
    ...typography.body,
    fontWeight: '600',
    color: colors.text.primary,
  },
  rosterTimingText: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 11,
  },
  rosterStatusCol: {
    alignItems: 'flex-end',
  },
  textHighlight: {
    color: colors.primary,
    fontWeight: '800',
  },
  textMuted: {
    color: colors.text.tertiary,
    fontStyle: 'italic',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background.primary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  modalTitle: {
    ...typography.h3,
    color: colors.text.primary,
  },
  modalCloseText: {
    ...typography.body,
    color: colors.danger,
    fontWeight: '600',
  },
  modalScroll: {
    padding: spacing.md,
  },
  modalFooter: {
    padding: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fieldLabel: {
    ...typography.caption,
    fontWeight: '700',
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  optionBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: borderRadius.md,
    backgroundColor: colors.surfaceCard,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  optionBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionBtnText: {
    ...typography.caption,
    color: colors.text.secondary,
    fontWeight: '600',
  },
  optionBtnTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  selectionList: {
    maxHeight: 140,
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  selectionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  selectionItemActive: {
    backgroundColor: `${colors.primary}15`,
  },
  selectionItemTitle: {
    ...typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  selectionItemSub: {
    ...typography.caption,
    color: colors.text.tertiary,
    fontSize: 10,
    marginTop: 1,
  },
});
